## CAPÍTULO II: DEL VEEDOR Y DEL LIQUIDADOR {-}

### Título 1. Del Veedor {-}

#### Párrafo 1. De la Nómina de Veedores {-}

##### Artículo 9°.- Estructura. {-}

La Nómina de Veedores estará integrada por las personas naturales nombradas en el cargo de Veedor por la Superintendencia, la que la mantendrá debidamente actualizada y a disposición del público a través de su página web.

##### Artículo 10.- Solicitud de inscripción. {-}

Toda persona natural interesada en ser nombrada Veedor podrá presentar su solicitud ante la Superintendencia. En ella deberá expresar si ejercería el cargo a nivel nacional o regional, acompañando los antecedentes que acrediten el cumplimiento de los requisitos señalados en el artículo 13 y una declaración jurada en que exprese no estar afecto a las prohibiciones contempladas en el artículo 17.

##### Artículo 11.- Inclusión en la Nómina de Veedores. {-}

El Veedor será incorporado a la nómina correspondiente mediante resolución dictada por la Superintendencia, una vez verificado el cumplimiento de los requisitos señalados en el artículo 13.

##### Artículo 12.- Menciones de la Nómina de Veedores. {-}

La referida Nómina contendrá las siguientes menciones respecto de cada Veedor:

1) Nombre completo, profesión, domicilio, datos de contacto y regiones en que ejercerá sus funciones.

2) Calificaciones obtenidas durante los últimos cinco años en el examen a que se refiere el artículo 14.

3) Número total de Procedimientos Concursales de Reorganización en que hubiere intervenido, con mención de aquellos en que se hubiere aprobado el Acuerdo de Reorganización, de los cinco principales acreedores y el sector o rubro de los Deudores en cada uno de ellos.

4) Honorario promedio percibido.

5) Registro de las sanciones aplicadas.

#### Párrafo 2. Del Veedor {-}

##### Artículo 13.- Requisitos. {-}

Podrá solicitar su inclusión en la Nómina de Veedores toda persona natural que cumpla con los siguientes requisitos:

1) Contar con un título profesional de contador auditor o de una profesión de a lo menos diez semestres de duración, otorgado por universidades del Estado o reconocidas por éste, o por la Corte Suprema, en su caso;

2) Contar con, a lo menos, cinco años de ejercicio de la profesión que haga valer;

3) Aprobar el examen para Veedores a que se refiere el artículo siguiente;

4) No estar afecto a alguna de las prohibiciones establecidas en el artículo 17, y

5) Otorgar, en tiempo y forma, la garantía señalada en el artículo 16.

##### Artículo 14.- Del examen de conocimientos. {-}

La Superintendencia convocará a un examen de conocimientos a las siguientes personas:

1) Postulantes a integrar la Nómina de Veedores.

2) Veedores que no hubieren asumido Procedimientos Concursales de Reorganización en un período de tres años contado desde su último examen rendido y aprobado.

3) Veedores que hubieren reprobado el examen en conformidad con lo establecido en el presente artículo.

El Veedor que hubiere reprobado el examen podrá rendirlo nuevamente en el período siguiente de examinación, en la fecha, hora y lugar que fije la Superintendencia. La inasistencia injustificada se entenderá como reprobación para todos los efectos legales.

El Veedor que hubiere reprobado el examen de repetición quedará suspendido de pleno derecho para asumir nuevos Procedimientos Concursales de Reorganización, aún como interventor, por un período de doce meses contado desde la notificación de su reprobación efectuada por correo electrónico, y hasta que apruebe un nuevo examen, debiendo rendirlo una vez terminado el período de suspensión, en la fecha de examinación correspondiente. Si reprueba nuevamente el examen de repetición, será excluido de la Nómina de Veedores.

El examen de conocimientos señalado en este artículo se convocará dos veces en cada año calendario y será regulado por la Superintendencia a través de normas de carácter general.

##### Artículo 15.- Responsabilidad. {-}

La responsabilidad civil del Veedor alcanzará hasta la culpa levísima y podrá perseguirse cuando corresponda, en cuyo caso se aplicarán las reglas del juicio sumario, una vez presentada la Cuenta Final de Administración, conforme a lo dispuesto en el Párrafo 2 del Título 3 del Capítulo II de esta ley, y sin perjuicio de la responsabilidad legal en que pudiere incurrir.

Sin perjuicio de lo anterior, si el Veedor no rindiere su Cuenta Final de Administración dentro del plazo regulado en el artículo 29, su responsabilidad civil también podrá perseguirse desde el vencimiento de dicho plazo.

##### Artículo 16.- Garantía de fiel desempeño. {-}

Todo Veedor mantendrá en la Superintendencia y mientras subsista su responsabilidad, una garantía por un monto de 2.000 unidades de fomento, con una vigencia mínima de tres años, renovable por igual período. En caso de no otorgarla en tiempo y forma, el Veedor no podrá asumir en nuevos Procedimientos Concursales de Reorganización.

La garantía podrá consistir en una boleta bancaria de garantía, póliza de seguro o cualquiera otra que la Superintendencia determine mediante norma de carácter general, la cual también establecerá la forma de rendirla, sus plazos, devolución, renovación y demás especificaciones aplicables.

La garantía a que se refiere este artículo tiene por objetivo caucionar el fiel desempeño de la actividad del Veedor y asegurar el correcto y cabal cumplimiento de todas sus obligaciones, incluyendo la eventual indemnización a que sea condenado en caso de hacerse efectiva su responsabilidad civil y el pago de las multas administrativas impuestas en su contra.

La Superintendencia hará efectiva la garantía y entregará su monto a requerimiento del tribunal que hubiere declarado la responsabilidad civil del Veedor, siempre que la resolución condenatoria se encuentre firme y ejecutoriada. Tratándose de multas impuestas por la propia Superintendencia, la resolución respectiva indicará el plazo en que el Veedor deberá pagarlas, el cual no podrá ser inferior a veinte días. Dicho plazo se contará desde que esa resolución se encuentre firme y ejecutoriada. Una vez transcurrido el término anterior sin verificarse el pago, la Superintendencia hará efectiva la garantía e imputará los fondos a la multa respectiva, restituyendo el saldo al Veedor, si correspondiere.
Sin perjuicio de lo anterior, si se ejecutare la garantía del Veedor conforme al inciso anterior, y una vez que se le restituya el saldo en su caso, se entenderá suspendido para asumir nuevos Procedimientos Concursales de Reorganización, y tendrá un plazo de veinte días para constituir una nueva garantía en los términos previstos en este artículo, manteniéndose la señalada suspensión mientras no la otorgue.

##### Artículo 17.- Prohibiciones. {-}

No podrán ser Veedores las siguientes personas:

1) Las que hayan sido condenadas por crimen o simple delito.

2) Los funcionarios de cualquier órgano de la Administración del Estado, los integrantes de las empresas públicas creadas por ley, los que ejerzan cargos de elección popular, y aquellos que presten cualquier tipo de servicios remunerados o no a la Superintendencia.

No obstante, no regirá esta incompatibilidad respecto de las personas que desempeñen labores docentes en instituciones de educación superior. Sin embargo, no se considerarán labores docentes las que correspondan a la dirección superior de una entidad académica, respecto de las cuales regirá la incompatibilidad a que se refiere este numeral.

3) Las que tuvieren incapacidad física o mental para ejercer el cargo.

4) Las que hubieren dejado de integrar la Nómina de Veedores en virtud de las causales de exclusión del artículo siguiente y sin perjuicio de lo dispuesto en el inciso final del mismo.

##### Artículo 18.- Causales de exclusión de la Nómina de Veedores. {-}

Los Veedores serán excluidos de su respectiva Nómina en los siguientes casos:

1) Por haber sido nombrados en contravención a lo dispuesto en este Título.

2) Por dejar de cumplir los requisitos enumerados en el artículo 13 de este Título.

3) Por adquirir para sí o para terceros, ya sea como persona natural o a través de una persona jurídica en la que el Veedor sea socio o Persona Relacionada, cualquier bien u obtener para sí alguna ventaja económica en los Procedimientos Concursales en que intervengan como Veedor.

4) Por enajenar o autorizar la enajenación de cualquier bien en los Procedimientos Concursales en que intervenga como Veedor a:

a) Sus Personas Relacionadas.

b) Alguna persona jurídica en que tenga interés económico directo o indirecto.

c) Socios o accionistas de una sociedad en la que el Veedor forme parte, o de las sociedades en las cuales tenga participación, salvo aquellas que se encuentren inscritas en el Registro de Valores y hagan oferta pública de ellos.

d) Personas con las que posea bienes en comunidad, con excepción de los copropietarios a que se refiere la ley Nº 19.537, sobre copropiedad inmobiliaria.

e) Sus dependientes.

f) Profesionales o técnicos que le presten servicios, sean éstos esporádicos o permanentes, cualquiera sea la forma en que estén constituidos.

5) Por haberse declarado judicialmente, mediante sentencia firme y ejecutoriada, su responsabilidad civil o penal en conformidad con el artículo 27.

6) Por renuncia presentada ante la Superintendencia, sin perjuicio de las obligaciones y responsabilidades por las funciones que ya hubiere asumido.

7) Por sentencia firme y ejecutoriada que rechace la Cuenta Final de Administración que debe presentar en conformidad a esta ley.

8) Por aplicación de la letra c) del artículo 339.

9) Por reprobación definitiva del examen de conocimientos a que se refiere el artículo 14.

10) Por muerte.

Producida alguna de las circunstancias señaladas en los números precedentes, la Superintendencia dictará la resolución de exclusión respectiva.

Sin perjuicio de lo anterior, en el evento que se produzcan algunas de las circunstancias previstas en los numerales 1), 2), 3), 4) y 8) anteriores, la Superintendencia deberá previamente representarla al Veedor para que éste presente sus descargos, dentro de los cinco días siguientes. Vencido el plazo señalado sin que se presente descargo alguno, la Superintendencia dictará la correspondiente resolución de exclusión. Si el Veedor presenta sus descargos, la Superintendencia podrá acogerlos o rechazarlos dictando la correspondiente resolución.

Las personas excluidas de la Nómina de Veedores por las causales de los números 1), 2) y 6) podrán solicitar, una vez transcurridos cinco años contados desde la fecha en que quedó firme el acto administrativo de exclusión, su reincorporación en la referida nómina, estándose a lo dispuesto en el presente Título.

Las personas excluidas de la Nómina de Veedores por cualquier otra causal no podrán volver a solicitar su inscripción en ella.

Lo anterior será sin perjuicio de la responsabilidad civil y penal que pudiere corresponderles en conformidad a la ley.

##### Artículo 19.- Reclamo de exclusión. {-}

El Veedor podrá reclamar de su exclusión de la respectiva nómina ante el juzgado de letras con competencia en lo civil de su domicilio dentro del plazo de diez días contado desde la notificación por carta certificada de la resolución que decida dicha exclusión.

El tribunal competente sujetará la tramitación del reclamo a las normas del procedimiento sumario, conforme a lo establecido en el artículo 341. Mientras se encuentre pendiente el reclamo de exclusión, el Veedor no podrá asumir nuevos Procedimientos Concursales.

Excluido el Veedor de la Nómina de Veedores, subsistirá la obligación de rendir cuenta de su gestión, así como la responsabilidad legal en que pudiere haber incurrido.

##### Artículo 20.- Designación del Veedor en los Procedimientos Concursales. {-}

Sólo podrá designarse Veedor a quien integre la Nómina de Veedores a la época de la dictación de la Resolución de Reorganización o de la Resolución de Liquidación, según corresponda.

##### Artículo 21.- Inhabilidades. {-}

No podrán ser nominados o designados Veedores en un Procedimiento Concursal de Reorganización:

1) Las Personas Relacionadas con el Deudor.

2) Los deudores y acreedores del Deudor o sus representantes, y todos los que tuvieren un interés directo o indirecto en el respectivo procedimiento.

3) Los que tuvieren objetada su Cuenta Final de Administración en un Procedimiento Concursal, siempre que hayan insistido en uno o más reparos.

4) Los que estuvieren suspendidos en conformidad a lo dispuesto en el artículo 14 o de acuerdo al número 5) del artículo 337 de esta ley.

##### Artículo 22.- Nominación del Veedor. {-}

Una vez que la Superintendencia reciba los antecedentes señalados en el artículo 55, notificará a los tres mayores acreedores del Deudor según la información entregada, dentro del día siguiente y por el medio más expedito. Esta notificación será certificada por el ministro de fe de la Superintendencia para todos los efectos legales.

Dentro del segundo día siguiente a la referida notificación, cada acreedor propondrá por escrito o por correo electrónico a un Veedor titular y a un Veedor suplente vigente en la Nómina de Veedores. Para estos efectos, cada acreedor será individualmente considerado sin distinción del monto de su crédito.

Dentro del día siguiente al señalado en el inciso anterior, la Superintendencia nominará como Veedor titular al que hubiere obtenido la primera mayoría de entre los propuestos para el cargo de titular por los acreedores, y como Veedor suplente a aquel que hubiere obtenido la primera mayoría de entre los propuestos para ese cargo. Si sólo respondiere un acreedor, se estará a su propuesta. Si respondieren todos o dos de ellos y la propuesta recayere en personas diversas, se estará a aquella del acreedor cuyo crédito sea superior.

En caso que no se reciban propuestas, la nominación tendrá lugar mediante sorteo ante la Superintendencia, en el que participarán aquellos Veedores que integren la terna propuesta por el Deudor en la solicitud señalada en el artículo 54 o, en su defecto, todos aquellos Veedores vigentes en la Nómina de Veedores a esa fecha. Los sorteos que efectúe la Superintendencia se regularán por medio de una norma de carácter general.

Excepcionalmente, si de los antecedentes señalados en el artículo 55, se acredita que un solo acreedor representa más del 50% del pasivo del deudor, la Superintendencia nominará al Veedor Titular y al Veedor Suplente propuesto por ese acreedor. En caso que dicho acreedor no propusiere al Veedor Titular y al Veedor Suplente, se estará a las reglas generales establecidas en los incisos anteriores.

El Veedor titular y el Veedor suplente nominados serán inmediatamente notificados por la Superintendencia por el medio más expedito.

El Veedor titular nominado deberá manifestar ante la Superintendencia si acepta el cargo a más tardar al día siguiente a su notificación y deberá jurar o prometer desempeñarlo fielmente. Al aceptar el cargo, deberá declarar sus relaciones con el Deudor o con los acreedores de éste, si las tuviere, y que no tiene impedimento o inhabilidad alguna para desempeñar el cargo.

Aceptado el cargo, la Superintendencia emitirá el Certificado de Nominación del Veedor, el cual será remitido directamente al tribunal competente, dentro del día siguiente a su emisión, para que éste designe a un Veedor nominado en la Resolución de Reorganización.
El Veedor podrá excusarse de aceptar una nominación ante la Superintendencia, debiendo expresar fundadamente y por escrito su justificación al día siguiente de su notificación. La Superintendencia resolverá dentro de los dos días siguientes con los antecedentes aportados por el Veedor y sin ulterior recurso. Si la excusa es desestimada, el Veedor deberá asumir como tal en el Procedimiento Concursal, entendiéndose legalmente aceptado el cargo desde que se resuelva la excusa y se emita el correspondiente Certificado de Nominación. Si la excusa es aceptada, la Superintendencia nominará al Veedor suplente como titular, nominándose a un nuevo Veedor suplente mediante sorteo.

##### Artículo 23.- De la cesación en el cargo. {-}

El Veedor cesará en el cargo por el término del Procedimiento Concursal de Reorganización o por cese anticipado en el mismo. Sin perjuicio de lo anterior, subsistirá su responsabilidad hasta la aprobación de su Cuenta Final de Administración.

##### Artículo 24.- Del cese anticipado en el cargo. {-}

Para los efectos de esta ley, se entenderá que el Veedor cesa anticipadamente en su cargo:
1) Por la revocación de la Junta de Acreedores.

2) Por remoción decretada por el tribunal.

3) Por renuncia aceptada por la Junta de Acreedores o, en su defecto, por el tribunal, la que deberá fundarse en una causa grave.

4) Por haber dejado de formar parte de la Nómina de Veedores, sin perjuicio de continuar en el cargo hasta que asuma el Veedor Suplente o el que se designe.

5) Por inhabilidad sobreviniente. El Veedor deberá dar cuenta al tribunal y a la Superintendencia, dentro del plazo de tres días, de la inhabilidad que le afecte. El incumplimiento de esta obligación será constitutivo de falta gravísima para los efectos de lo dispuesto en el número 8) del artículo 18.

El Veedor suplente asumirá dentro de los dos días siguientes a la cesación en el cargo del Veedor titular, cualquiera sea la causa del cese.

El Veedor que haya cesado anticipadamente en su cargo deberá rendir cuenta de su gestión y hacer entrega de los antecedentes del Procedimiento Concursal al Veedor suplente, dentro de los diez días siguientes a la fecha en que este último haya asumido. En caso de incumplimiento, el tribunal competente, de oficio o a petición de cualquier interesado, requerirá el cumplimiento según lo previsto en el artículo 238 del Código de Procedimiento Civil, en cuyo caso la multa será de 10 a 200 unidades tributarias mensuales. Sin perjuicio de lo anterior, la Superintendencia podrá aplicar las sanciones que correspondan.

##### Artículo 25.- Deberes del Veedor. {-}

La función principal del Veedor es propiciar los acuerdos entre el Deudor y sus acreedores, facilitando la proposición y negociación del Acuerdo. Para estos efectos, el Veedor podrá citar al Deudor y a sus acreedores en cualquier momento desde la publicación de la Resolución de Reorganización hasta la fecha en que debe acompañar al tribunal competente el informe que regula el numeral 8) del artículo 57, con el propósito de facilitar los acuerdos entre las partes y propiciar la celebración de un Acuerdo de Reorganización Judicial en los términos regulados en la presente ley.

En el ejercicio de sus funciones deberá especialmente:

1) Imponerse de los libros, documentos y operaciones del Deudor.

2) Incorporar y publicar en el Boletín Concursal copia de todos los antecedentes y resoluciones que esta ley le ordene.

3) Realizar las inscripciones y notificaciones que disponga la Resolución de Reorganización.

4) Realizar las labores de fiscalización y valorización que se le imponen en los artículos 72 y siguientes, referidas a la continuidad del suministro, a la venta necesaria de activos y a la obtención de nuevos recursos.

5) Arbitrar las medidas necesarias en el procedimiento de determinación del pasivo establecido en los artículos 70 y 71.

6) Realizar la calificación de los poderes para comparecer en las Juntas de Acreedores e informar al tribunal competente sobre la legalidad de éstos, cuando corresponda.

7) Impetrar las medidas precautorias y de conservación de los activos del Deudor que sean necesarias para resguardar los intereses de los acreedores, sin perjuicio de los acuerdos que éstos puedan adoptar.

8) Dar cuenta al tribunal competente y a la Superintendencia de cualquier acto o conducta del Deudor que signifique una administración negligente o dolosa de sus negocios y, con la autorización de dicho tribunal, adoptar las medidas necesarias para mantener la integridad de los activos, cuando corresponda.

9) Rendir mensualmente cuenta de su actuación y de los negocios del Deudor a la Superintendencia, y presentar las observaciones que le merezca la administración de aquél. Esta cuenta será enviada, además, por correo electrónico a cada uno de los acreedores.

10) Ejecutar todos los actos que le encomiende esta ley.

##### Artículo 26.- Delegación de funciones. {-}

El Veedor sólo podrá delegar sus funciones, manteniendo su responsabilidad y a su costa, en otros Veedores vigentes en la Nómina de Veedores, con igual competencia territorial.
La referida delegación deberá efectuarse por instrumento público, en el que conste la aceptación del delegado, el que será agregado al expediente y notificado mediante su publicación en el Boletín Concursal.

##### Artículo 27.- Concierto Previo. {-}

El Veedor que se concertare con el Deudor, con algún acreedor o un tercero para proporcionarle alguna ventaja indebida o para obtenerla para sí, será sancionado de conformidad a lo establecido en el Párrafo 7 del Título IX del Libro Segundo del Código Penal.

##### Artículo 28.- Honorarios del Veedor. {-}

Los honorarios del Veedor serán convenidos entre éste, los tres principales acreedores y el Deudor y serán de cargo de este último. Estos honorarios gozarán de la preferencia establecida en el número 4 del artículo 2472 del Código Civil, sin perjuicio de lo prescrito en el número 3) del artículo 118 de esta ley.

##### Artículo 29.- De la Cuenta Final. {-}

El Veedor rendirá cuenta final de su gestión en el plazo de treinta días contado desde la Resolución que aprueba el Acuerdo de Reorganización Judicial o desde la Resolución de Liquidación, en su caso. Al respecto, le será plenamente aplicable lo dispuesto en el Párrafo 2 del Título 3 del Capítulo II de esta ley.

### Título 2. Del Liquidador {-}

#### Párrafo 1. De la Nómina de Liquidadores {-}

##### Artículo 30.- Estructura. {-}

La Nómina de Liquidadores estará integrada por todas las personas naturales nombradas como tales por la Superintendencia, la que deberá mantenerla debidamente actualizada y a disposición del público a través de su página web.

##### Artículo 31.- Norma general. {-}

Será aplicable a los Liquidadores lo dispuesto en el Título 1 del Capítulo II de la presente ley respecto de los Veedores, en todo aquello que no esté expresamente regulado en el presente Título y, en todo caso, siempre que no sea contrario a la naturaleza de la función que desempeñan.

##### Artículo 32.- Requisitos. {-}

Podrá ser Liquidador y solicitar su inclusión en la Nómina de Liquidadores, toda persona natural que cumpla con los siguientes requisitos:

1) Contar con un título profesional de contador auditor o de una profesión de a lo menos diez semestres de duración, otorgado por universidades del Estado o reconocidas por éste, o por la Corte Suprema, en su caso.

2) Contar con, a lo menos, cinco años de ejercicio de la profesión que haga valer.

3) Aprobar un examen de conocimientos para Liquidadores, en los términos del artículo 14.

4) No estar afecto a alguna de las prohibiciones establecidas en el artículo 17.

5) Otorgar, en tiempo y forma, la garantía señalada en el artículo 16.

##### Artículo 33.- Menciones de la Nómina de Liquidadores. {-}

Además de las menciones señaladas en el artículo 12, la Nómina de Liquidadores deberá contener el régimen de descuento de honorarios ofrecido por el Liquidador y su respectiva vigencia, respecto de la tabla del artículo 40.

Asimismo, deberá señalar el número de Procedimientos Concursales de Liquidación en que cada Liquidador hubiere intervenido, la lista de los cinco principales acreedores en cada uno de ellos, el porcentaje de Procedimientos Concursales de Liquidación con Cuenta Final de Administración aprobada y el sector o rubro del Deudor en cada uno de dichos procedimientos.

##### Artículo 34.- Causales de exclusión de la Nómina de Liquidadores. {-}

Además de las causales de exclusión señaladas en el artículo 18, será excluido de la Nómina de Liquidadores aquel que se negare a asumir un Procedimiento Concursal de Liquidación sin causa justificada.

Para estos efectos, se entenderá como causa justificada las señaladas en esta ley.

#### Párrafo 2. Del Liquidador {-}

##### Artículo 35.- Responsabilidad. {-}

La responsabilidad civil de los Liquidadores alcanzará hasta la culpa levísima y se podrá perseguir, cuando corresponda, en juicio sumario una vez presentada la Cuenta Final de Administración, conforme lo dispuesto en los artículos 49 y siguientes de esta ley, y sin perjuicio de la responsabilidad legal en que pudiere incurrir.

Sin perjuicio de lo anterior, si el Liquidador no rindiere su Cuenta Final de Administración dentro del plazo regulado en el artículo 50, su responsabilidad civil también podrá perseguirse desde el vencimiento de dicho plazo.

##### Artículo 36.- Deberes del Liquidador. {-}

El Liquidador representa judicial y extrajudicialmente los intereses generales de los acreedores y los derechos del Deudor en cuanto puedan interesar a la masa, sin perjuicio de las facultades de aquéllos y de éste determinadas por esta ley.

En el ejercicio de sus funciones, el Liquidador deberá especialmente, con arreglo a esta ley:

1) Incautar e inventariar los bienes del Deudor.

2) Liquidar los bienes del Deudor.

3) Efectuar los repartos de fondos a los acreedores en la forma dispuesta en el Párrafo 3 del Título 5 del Capítulo IV de esta ley.

4) Cobrar los créditos del activo del Deudor.

5) Contratar préstamos para solventar los gastos del Procedimiento Concursal de Liquidación.

6) Exigir rendición de cuentas de cualquiera que haya administrado bienes del Deudor.

7) Reclamar del Deudor la entrega de la información necesaria para el desempeño de su cargo.

8) Registrar sus actuaciones y publicar las resoluciones que se dicten en el Procedimiento Concursal de Liquidación en el Boletín Concursal.

9) Depositar a interés en una institución financiera los fondos que perciba, en cuenta separada para cada Procedimiento Concursal de Liquidación y a nombre de éste, y abrir una cuenta corriente con los fondos para solventarlo.

10) Ejecutar los acuerdos legalmente adoptados por la Junta de Acreedores dentro del ámbito de su competencia.

11) Cerrar los libros de comercio del Deudor, quedando responsable por ello frente a terceros desde la dictación de la Resolución de Liquidación.

12) Transigir y conciliar los créditos laborales con el acuerdo de la Junta de Acreedores, según lo dispone el artículo 246 de esta ley.

13) Ejercer las demás facultades y cumplir las demás obligaciones que le encomienda la presente ley.

##### Artículo 37.- Nominación del Liquidador. {-}

Presentada una solicitud de inicio de Procedimiento Concursal de Liquidación ante el tribunal competente, la Superintendencia nominará al Liquidador conforme al procedimiento establecido en el presente artículo, salvo en el caso previsto en el número 3 del artículo 120.

Tratándose de una solicitud de Liquidación Voluntaria, el Deudor acompañará a la Superintendencia copia de la respectiva solicitud con cargo del tribunal competente o de la Corte de Apelaciones correspondiente y copia de la nómina de acreedores y sus créditos, de acuerdo a lo establecido en el artículo 115 de esta ley.

Tratándose de una solicitud de Liquidación Forzosa, el acreedor peticionario acompañará a la Superintendencia copia de la respectiva solicitud con cargo del tribunal competente o de la Corte de Apelaciones correspondiente y copia de la nómina de acreedores y sus créditos que haya acompañado el Deudor, en su caso, de acuerdo a lo establecido en el artículo 120 de esta ley.

Acompañados los antecedentes antes señalados, la Superintendencia notificará a los tres mayores acreedores del Deudor, que no sean Personas Relacionadas de éste, según la información entregada, dentro del día siguiente y por el medio más expedito, lo que será certificado por un ministro de fe de la Superintendencia.

Dentro del segundo día siguiente a la referida notificación, cada acreedor propondrá por escrito o por correo electrónico a un Liquidador titular y a un Liquidador suplente vigentes en la Nómina de Liquidadores. Para estos efectos, cada acreedor será individualmente considerado, sin distinción del monto de su crédito.

Dentro del día siguiente al señalado en el inciso anterior, la Superintendencia nominará como Liquidador titular al que hubiere obtenido la primera mayoría de entre los propuestos para ese cargo por los acreedores, y como suplente a aquel que hubiere obtenido la primera mayoría de entre los propuestos para ese cargo. Si sólo respondiere un acreedor, se estará a su propuesta. Si respondieren todos o dos de ellos y la propuesta recayere en personas diversas, se estará a aquella del acreedor cuyo crédito sea superior. En caso que no se reciban propuestas, la nominación tendrá lugar mediante sorteo ante la Superintendencia, en el que participarán todos aquellos Liquidadores vigentes en la Nómina de Liquidadores a esa fecha.

Los sorteos que efectúe la Superintendencia se regularán por medio de una norma de carácter general.

Excepcionalmente, si de los antecedentes acompañados a la Superintendencia por el Deudor o acreedor peticionario, según corresponda, se acredita que un solo acreedor representa más del 50% del pasivo del deudor, la Superintendencia nominará al Liquidador titular y al suplente propuesto por dicho acreedor. En caso que dicho acreedor no propusiere al Liquidador titular y al suplente, se estará a las reglas generales establecidas en los incisos anteriores.

Los Liquidadores titular y suplente nominados serán inmediatamente notificados por la Superintendencia por el medio más expedito.

El Liquidador titular nominado deberá manifestar ante la Superintendencia, a más tardar al día siguiente de su notificación, si acepta el cargo y deberá jurar o prometer desempeñarlo fielmente. Al aceptar el cargo deberá declarar sus relaciones con el Deudor y los acreedores de éste, y que no tiene impedimento o inhabilidad alguna para desempeñarlo.

El Liquidador podrá excusarse ante la Superintendencia de aceptar una nominación, debiendo expresar fundadamente y por escrito sus justificaciones, al día siguiente de su notificación. La Superintendencia resolverá dentro de los dos días siguientes con los antecedentes aportados por el Liquidador y sin ulterior recurso. Si la excusa es desestimada, el Liquidador deberá asumir como tal en el Procedimiento Concursal de Liquidación, entendiéndose legalmente aceptado el cargo desde que se resuelva la excusa y se emita el correspondiente Certificado de Nominación. Si la excusa es aceptada, la Superintendencia nominará al Liquidador suplente como titular, nominándose a un nuevo Liquidador suplente mediante sorteo.

Aceptado el cargo, la Superintendencia emitirá el Certificado de Nominación del Liquidador, el cual será remitido directamente al tribunal competente, dentro del día siguiente a su emisión, para que éste lo designe como Liquidador en carácter de provisional en la Resolución de Liquidación.

##### Artículo 38.- Cese anticipado en el cargo. {-}

El Liquidador cesará anticipadamente en el cargo por no haberse confirmado su nominación por la Junta de Acreedores; por haberse aprobado un Acuerdo de Reorganización Judicial o un Acuerdo de Reorganización Simplificado que termine con el Procedimiento Concursal de Liquidación, o por lo dispuesto en los artículos 23 y 24, que serán aplicables, en lo que corresponda, al Liquidador.

Si el Liquidador titular cesare anticipadamente en el cargo asumirá el suplente, sin perjuicio de la facultad de la Junta de Acreedores de designar uno nuevo. Si no pudiere asumir el Liquidador suplente, la Superintendencia deberá citar a Junta Extraordinaria de Acreedores con el fin de que se designe un Liquidador titular y a uno suplente, en caso que los acreedores no los hubieren designado. Si dicha junta no se celebra por falta de quórum, la Superintendencia hará la designación por sorteo.

Los Liquidadores que fueren designados de conformidad a este artículo deberán asumir aun cuando el Procedimiento Concursal de Liquidación no tuviere bienes o fondos por repartir.

##### Artículo 39.- Honorarios del Liquidador. {-}

Los honorarios a percibir por los Liquidadores en los Procedimientos Concursales de Liquidación a su cargo se sujetarán a las disposiciones siguientes:

1) Se determinarán de conformidad a la tabla progresiva por tramos prevista en el artículo siguiente.

2) Tendrán la naturaleza de remuneración única y de gasto de administración del Procedimiento Concursal de Liquidación para todos los efectos legales a que hubiere lugar.
Serán de cargo del Liquidador todos los gastos correspondientes al ejercicio de su cargo, así como los honorarios de todos sus asesores jurídicos, técnicos, administrativos o de cualquier otra índole que hubiere contratado para el desarrollo de su actividad.

Si el domicilio del Deudor fuere distinto al del Liquidador, los gastos de traslado y otros necesarios para el Procedimiento Concursal de Liquidación se considerarán gastos de administración y deberán ser ratificados por la Junta o, en subsidio, por el tribunal competente.

3) No se incluirán aquellos honorarios que se devenguen en caso de la continuación de actividades económicas del Deudor en los términos de los artículos 232 y 233 de esta ley.
4) Sólo podrán pagarse honorarios adicionales si los acreedores lo acuerdan en Junta de Acreedores. El pago de este aumento será de cargo exclusivo de aquellos acreedores que lo hubieren votado favorablemente.

5) Los honorarios se calcularán considerando los montos reservados de conformidad a lo dispuesto en los números 2 y 3 del artículo 247, pero sólo se pagarán los correspondientes a los fondos efectivamente repartidos de acuerdo a la tabla progresiva por tramos prevista en el artículo siguiente.

6) El Liquidador deberá retener en instrumentos de renta fija, a nombre del Deudor sujeto a un Procedimiento Concursal de Liquidación, el 10% del honorario que le correspondería percibir en cada reparto. Estos honorarios sólo podrán ingresar al patrimonio del Liquidador una vez presentada la Cuenta Final de Administración, conforme a lo dispuesto en los artículos 49 y siguientes. Si la señalada cuenta es rechazada por sentencia firme, estos fondos serán restituidos a la masa, debiendo ser destinados para el pago de los honorarios del nuevo Liquidador designado en caso que no hubiere fondos por repartir.

7) Podrán acordarse en Junta de Acreedores, con Quórum Simple, anticipos de honorarios al Liquidador, los que no podrán exceder del 10% de los ingresos en dinero efectivo que haya producido el Procedimiento Concursal de Liquidación al momento del anticipo.

8) Si el Liquidador cesa anticipadamente en el cargo conforme al artículo 38, sus honorarios y los de quien lo reemplace serán acordados entre el Liquidador respectivo y la Junta de Acreedores. Faltando dicho acuerdo, resolverá el tribunal competente sin ulterior recurso.

9) Se prohíbe al Liquidador o a sus Personas Relacionadas recibir a cualquier título otro pago distinto de los regulados en el presente artículo, por parte de algún acreedor o de sus Personas Relacionadas.

##### Artículo 40.- Tabla de Honorarios. {-}

El honorario único a que se refiere el artículo anterior deberá pagarse al Liquidador en su equivalente en pesos a la fecha del respectivo reparto, de conformidad a la tabla progresiva por tramos regulada a continuación:

1) Sobre la parte que exceda de 0 y no sobrepase de 2.000 unidades de fomento, 20%.

2) Sobre la parte que exceda de 2.000 y no sobrepase las 4.000 unidades de fomento, 15%.

3) Sobre la parte que exceda de 4.000 y no sobrepase las 8.000 unidades de fomento, 11%.

4) Sobre la parte que exceda de 8.000 y no sobrepase las 16.000 unidades de fomento, 8%.

5) Sobre la parte que exceda de 16.000 y no sobrepase las 32.000 unidades de fomento, 6%.

6) Sobre la parte que exceda de 32.000 y no sobrepase las 64.000 unidades de fomento, 4%.

7) Sobre la parte que exceda de 64.000 y no sobrepase las 130.000 unidades de fomento, 3%.

8) Sobre la parte que exceda de 130.000 y no sobrepase las 260.000 unidades de fomento, 2,25%.

9) Sobre la parte que exceda de 260.000 y no sobrepase las 520.000 unidades de fomento, 1,75%.

10) Sobre la parte que exceda de 520.000 y no sobrepase las 1.000.000 de unidades de fomento, 1,5%.

11) Sobre la parte que exceda de 1.000.000 de unidades de fomento, 1%.

El primer tramo se calculará sobre los ingresos del Procedimiento Concursal de Liquidación cuando no hubiere repartos o, si habiendo repartos, correspondiere al Liquidador un honorario inferior a 30 unidades de fomento y, en este caso, el honorario no podrá exceder de esa cantidad.

Para la determinación del honorario que corresponda al Liquidador en cada reparto, se deberá calcular previamente la cantidad que le corresponda por honorarios y luego aplicar la tabla precedente en la forma progresiva descrita, a partir del respectivo tramo. En consecuencia, para la aplicación de la tabla y determinación del porcentaje del honorario que le corresponde en cada reparto, deberá considerarse el monto total distribuido en repartos anteriores.

Si luego de practicada la diligencia de incautación y confección de inventario a que se refiere el numeral 2) del artículo 163, se constatare por el Liquidador que el Deudor carece de bienes, o que éstos son insuficientes para el pago de los honorarios que pudieren corresponderle, éste sólo tendrá derecho a una remuneración de 30 unidades de fomento, que serán pagadas por la Superintendencia con cargo a su presupuesto.

##### Artículo 41.- Contrataciones especializadas. {-}

No obstante lo dispuesto en el artículo anterior y previo acuerdo adoptado en Junta de Acreedores con Quórum Calificado, el Liquidador podrá contratar, con cargo a los gastos del Procedimiento Concursal de Liquidación, personas naturales o jurídicas para que efectúen actividades especializadas debidamente calificadas como tales por la Junta de Acreedores.
Con todo, podrán realizar dichas contrataciones aun antes de la Junta Constitutiva, siempre y cuando sea estrictamente necesario, previa autorización del tribunal.

Las actividades especializadas deberán referirse directamente al cuidado y mantención del activo del Deudor, a la recuperación y realización del mismo y a su entrega material. La contratación se hará previo informe del Liquidador, el cual contendrá los fundamentos de la misma, el grado y alcance de la actividad y la forma en que se beneficiarán los acreedores o se evitarán perjuicios al activo incautado.

El Liquidador, o sus Personas Relacionadas, no podrán tener participación alguna en los actos o contratos que se ejecuten o celebren en conformidad a este artículo, salvo en cuanto a sus actividades como Liquidador en el Procedimiento Concursal de Liquidación, y tampoco podrán participar como socios, accionistas, trabajadores o asesores de las personas jurídicas que sean contratadas para las actividades o informes indicados. La transgresión a esta prohibición constituirá causa gravísima para efectos de la letra c) del artículo 339.

### Título 3. De las disposiciones comunes al Veedor y Liquidador {-}

##### Artículo 42.- Regla general. {-}

Una misma persona natural no podrá estar inscrita en la Nómina de Veedores y en la Nómina de Liquidadores.

##### Artículo 43.- De la inclusión en la Nómina de Veedores y en la Nómina de Liquidadores. {-}

El registro de una persona en la Nómina de Veedores, no importará su inclusión en la Nómina de Liquidadores, ni viceversa.

##### Artículo 44.- Prohibiciones relativas del Veedor o Liquidador. {-}

Sin perjuicio de las demás prohibiciones establecidas en esta ley, los Veedores y Liquidadores no podrán intervenir en Procesos Concursales de Reorganización o Liquidación en que no hubieren sido designados, salvo las actuaciones que les correspondan como acreedor con anterioridad al Procedimiento Concursal respectivo, de representante legal en conformidad al artículo 43 del Código Civil, y de lo previsto en el artículo 26 de esta ley. La contravención a la presente prohibición constituye una infracción gravísima para los efectos del número 8) del artículo 18.

Asimismo, los Veedores y Liquidadores no podrán contratar por sí, a través de terceros o de una persona jurídica en la que sean socios o Personas Relacionadas, con cualquier Deudor sometido a un Procedimiento Concursal.

##### Artículo 45.- De la exclusión de la Nómina Veedores y de la Nómina de Liquidadores. {-}

La exclusión de la Nómina de Veedores supondrá necesariamente impedimento para incorporarse a la Nómina de Liquidadores, y viceversa, salvo que se funde en el número 6) del artículo 18, en cuyo caso, excepcionalmente, podrá solicitarse la incorporación a la otra nómina, antes del plazo de 5 años señalado en el inciso cuarto del referido artículo, previa autorización de la Superintendencia.

#### Párrafo 1. De las cuentas provisorias {-}

##### Artículo 46.- Contenido. {-}

La Superintendencia, mediante norma de carácter general, fijará la forma y contenidos obligatorios de las cuentas provisorias que deba rendir el Liquidador, las que deberán incluir, a lo menos, un desglose detallado de los ingresos y gastos durante los últimos tres meses, con observancia de la normativa contable, tributaria y financiera aplicable.

##### Artículo 47.- Oportunidad y revisión. {-}

Las cuentas provisorias deberán publicarse mensualmente en el Boletín Concursal y rendirse ante la Junta de Acreedores respectiva, la que deberá aprobarlas o rechazarlas en esa misma sesión.

A partir de la publicación señalada en el inciso anterior, los acreedores podrán formular a la Superintendencia sus observaciones a la cuenta provisoria publicada, para que ésta las incluya en el Boletín Concursal dentro del plazo de cinco días contado desde la recepción de aquellas. El Liquidador deberá responder las observaciones en la próxima Junta de Acreedores que se celebre y, a continuación, se resolverá su aprobación o rechazo.

La aprobación de la cuenta provisoria por la Junta de Acreedores no impedirá, en su caso, objetar la Cuenta Final de Administración, respecto de las partidas incluidas en ella.

##### Artículo 48.- No celebración de la Junta de Acreedores. {-}

Si la Junta de Acreedores no se celebra por falta de quórum, el Liquidador notificará dicha circunstancia en el Boletín Concursal dentro del plazo de dos días.

#### Párrafo 2. De la Cuenta Final de Administración {-}

##### Artículo 49.- Contenido. {-}

La Superintendencia fijará la forma y contenidos obligatorios de la Cuenta Final de Administración mediante norma de carácter general, con observancia de la normativa contable, tributaria y financiera aplicable.

##### Artículo 50.- Oportunidad. {-}

El Liquidador deberá acompañar al Tribunal y a la Superintendencia su Cuenta Final de Administración dentro de los treinta días siguientes a que se verifique cualquiera de las circunstancias que a continuación se señalan:

1) Vencimiento de los plazos legales de realización de bienes.

2) Agotamiento de los fondos o pago íntegro de los créditos reconocidos.

3) Cese anticipado de su cargo.

##### Artículo 51.- Rendición de la Cuenta. {-}

Una vez acompañada su Cuenta Final de Administración al tribunal competente y a la Superintendencia, el Liquidador deberá citar a Junta de Acreedores a efectos de rendirla, explicar su contenido, las conclusiones y acreditar la retención del porcentaje de honorarios a percibir de conformidad a lo dispuesto en el número 7) del artículo 39. La Superintendencia podrá concurrir a dicha Junta con derecho a voz.

La citación deberá publicarse en el Boletín Concursal dentro de los cinco días siguientes a la resolución que tuvo por acompañada la Cuenta Final de Administración ante el Tribunal, e incluirá el día, hora y lugar en que se celebrará la Junta de Acreedores. Entre la fecha de publicación de la citación y de celebración de la Junta de Acreedores deberán transcurrir no menos de diez ni más de veinticinco días. La citación incluirá también una copia de la Cuenta Final de Administración.

Dicha Junta se celebrará con los acreedores que asistan.

##### Artículo 52.- De la objeción. {-}

Podrán objetar la Cuenta Final de Administración del Liquidador el Deudor, cualquier acreedor y la Superintendencia.

Las objeciones se presentarán ante la Superintendencia dentro de los cinco días siguientes a la fecha en que se celebró o debió celebrarse la respectiva Junta de Acreedores. Si el objetante fuese la Superintendencia, su objeción será publicada en el Boletín Concursal en el mismo plazo antes señalado.

En caso de no deducirse objeciones oportunamente, el Liquidador o la Superintendencia solicitarán al tribunal competente que tenga por aprobada la Cuenta Final de Administración para todos los efectos legales.

Si se presentaren objeciones, se observarán las normas que siguen:

1) Una vez vencido el plazo señalado en el inciso segundo, la Superintendencia requerirá informe al Liquidador de todas las objeciones presentadas o publicadas en una única resolución, la que se notificará por correo electrónico al Liquidador y se publicará en el Boletín Concursal.

2) El Liquidador dispondrá de diez días contados desde la notificación de la resolución antes indicada para contestar en una sola presentación todas las objeciones planteadas. En su presentación, el Liquidador podrá incluir correcciones a la Cuenta Final de Administración objetada, caso en el cual acompañará el texto definitivo que las refleje.

3) Si el Liquidador no efectúa presentación alguna en el plazo antes indicado, se entenderá suspendido de pleno derecho para asumir en los procedimientos regidos por esta ley mientras la o las objeciones no sean resueltas.

4) Transcurrido el plazo señalado en el número 2), se haya presentado o no el informe del Liquidador, los objetantes dispondrán de tres días para insistir en sus objeciones.

5) Si no se presentaren insistencias, se tendrá por aprobada la Cuenta Final de Administración.

6) En caso de insistencia, la Superintendencia remitirá al tribunal competente, dentro del plazo de diez días, un informe que contendrá las objeciones planteadas, la contestación del Liquidador si la hubiere, y su opinión en cuanto a si los hechos afectan decisivamente el patrimonio concursado, si implican un grave perjuicio para los acreedores y/o el Deudor, o si reflejan una manifiesta e inexcusable inobservancia del Liquidador a su deber de cuidado. El referido informe establecerá si el Liquidador quedará suspendido para asumir en nuevos Procedimientos Concursales.

7) El tribunal competente apreciará los antecedentes aportados de acuerdo a las normas de la sana crítica y pronunciará su resolución dentro de los quince días siguientes a la entrega del informe que indica el número anterior.

8) Si la resolución desechare en todas sus partes la o las objeciones deducidas, condenará al o los objetantes en costas, quienes responderán solidariamente de ellas, salvo que el tribunal competente estime que hubo motivo plausible para litigar. La misma regla se aplicará en caso que la resolución rechace una o más objeciones y acoja otras, respondiendo solidariamente todas las partes vencidas de la condena en costas. Tratándose del Deudor, responderán solidariamente de esas costas su abogado patrocinante y sus mandatarios judiciales.

9) La resolución del tribunal competente que acoja una o más objeciones insistidas, señalará las medidas que el Liquidador deberá ejecutar para subsanar, reparar o corregir los defectos advertidos. Si la resolución rechaza la Cuenta Final de Administración deberá designar al Liquidador suplente como titular, de acuerdo con lo establecido en el inciso segundo del artículo 38.

Contra esta resolución procederá el recurso de apelación, el que se concederá en el solo efecto devolutivo. Contra la resolución que rechace una o más objeciones insistidas no procederá recurso alguno.

Una vez firme la sentencia que rechace la Cuenta Final de Administración, la Superintendencia excluirá al Liquidador de la Nómina de Liquidadores, de conformidad a lo establecido en el artículo 34 de esta ley.

##### Artículo 53.- Ejecución de las resoluciones que rechazan la Cuenta Final de Administración.  {-}

La ejecución de estas resoluciones se sujetará a las siguientes reglas:

1) Si la resolución ordena al Liquidador a quien se le rechazó la Cuenta restituir a la masa una suma de dinero, se procederá de la siguiente forma:

a) Tendrá el plazo de treinta días, prorrogable por igual período, desde que la resolución se encuentra firme y ejecutoriada para dar cumplimiento a lo resuelto.

b) Si no efectuare la restitución señalada, el tribunal competente certificará esa omisión, de oficio o a petición de parte, y comunicará tal circunstancia a la Superintendencia.

c) Con esa certificación, la Superintendencia hará efectiva la garantía de fiel desempeño referida en el artículo 16 de esta ley, consignando los fondos en el tribunal competente.

2) Si la resolución ordena al Liquidador cuya Cuenta se rechazó una medida distinta a la de restituir a la masa una suma de dinero, se procederá de la siguiente manera:

a) El Liquidador cuya Cuenta se rechazó ejecutará lo resuelto dentro del mismo plazo indicado en el número anterior o en aquél que fije el tribunal en su resolución.

b) El honorario del nuevo Liquidador designado se determinará de común acuerdo con la Junta de Acreedores o, en su defecto, por el tribunal competente, y se pagará de acuerdo a lo establecido en el número 6 del artículo 39.

En todos los casos señalados en este artículo, el Liquidador cuya cuenta se rechazó podrá solicitar una prórroga ante el tribunal competente, por una sola vez y por un máximo de treinta días, para dar cumplimiento a lo resuelto.

