## CAPÍTULO III: DEL PROCEDIMIENTO CONCURSAL DE REORGANIZACIÓN {-}

### Título 1. Del inicio del Procedimiento Concursal de Reorganización Judicial {-}

##### Artículo 54.- Ámbito de aplicación e inicio del Procedimiento Concursal de Reorganización Judicial. {-}

El Procedimiento Concursal de Reorganización Judicial será aplicable sólo a la Empresa Deudora, que para efectos de este Capítulo se denominará indistintamente Empresa Deudora o Deudor.

El Procedimiento Concursal de Reorganización se iniciará mediante la presentación de una solicitud por la Empresa Deudora ante el tribunal correspondiente a su domicilio.

Un modelo de dicha solicitud se regulará por la Superintendencia mediante una norma de carácter general, que estará disponible en sus dependencias, en su sitio web y en las dependencias de los tribunales con competencia en Procedimientos Concursales de conformidad a lo establecido en el artículo 3º.

##### Artículo 55.- Antecedentes para la nominación del Veedor. {-}

Para los efectos de la nominación de los Veedores titular y suplente, el Deudor deberá presentar a la Superintendencia una copia del documento indicado en el artículo anterior, con el respectivo cargo del tribunal competente o de la Corte de Apelaciones correspondiente. Además, deberá acompañar un certificado emitido por un auditor independiente al Deudor, inscrito en el Registro de Auditores Externos de la Superintendencia de Valores y Seguros. Este certificado se extenderá conforme a la información disponible suministrada por el Deudor y deberá contener un estado de sus deudas, con expresión del nombre, domicilio y correo electrónico de los acreedores o de sus representantes legales, en su caso; de la naturaleza de los respectivos títulos, y del monto de sus créditos, indicando el porcentaje que cada uno representa en el total del pasivo, con expresión de los tres mayores acreedores, excluidas las Personas Relacionadas al Deudor. La nominación de los Veedores titular y suplente se realizará según el procedimiento establecido en el artículo 22 y, una vez concluido, la Superintendencia extenderá el respectivo Certificado de Nominación contemplado en dicha disposición.

##### Artículo 56.- Antecedentes que deberá acompañar el Deudor. {-}

Aceptada la nominación por el Veedor titular y suplente, la Superintendencia remitirá al tribunal competente el Certificado de Nominación correspondiente. Paralelamente, el Deudor acompañará lo siguiente:

1) Relación de todos sus bienes, con expresión de su avalúo comercial, del lugar en que se encuentren y de los gravámenes que los afecten. Deberá señalar, además, cuáles de estos bienes tienen la calidad de esenciales para el giro de la Empresa Deudora;

2) Relación de todos aquellos bienes de terceros constituidos en garantía en favor del Deudor. Deberá señalar, además, cuáles de estos bienes tienen la calidad de esenciales para el giro de la Empresa Deudora;

3) Relación de todos aquellos bienes que se encuentren en poder del Deudor en una calidad distinta a la de dueño;

4) El certificado a que hace referencia el artículo 55, para la determinación del pasivo afecto a los Acuerdos de Reorganización Judicial. El pasivo que se establezca en este certificado deberá considerar el estado de deudas del Deudor, con una fecha de cierre no superior a cuarenta y cinco días anteriores a esta presentación, con indicación expresa de los créditos que se encuentren garantizados con prenda o hipoteca y el avalúo comercial de los bienes sobre los que recaen las garantías. Este certificado servirá de base para determinar todos los quórum de acreedores que se necesiten en la adopción de cualquier acuerdo, hasta que se confeccione la nómina de créditos reconocidos, conforme al procedimiento establecido en el Párrafo 2 del Título 1 del Capítulo III de esta ley, con sus respectivas ampliaciones o modificaciones, si existieren, y

5) Si el Deudor llevare contabilidad completa, presentará el balance correspondiente a su último ejercicio y un balance provisorio que contenga la información financiera y contable, con una fecha de cierre no superior a cuarenta y cinco días anteriores a esta presentación.

Si se tratare de una persona jurídica, los documentos referidos serán firmados por sus representantes legales.

##### Artículo 57.- Resolución de Reorganización. {-}

Dentro del quinto día de efectuada la presentación señalada en el artículo anterior, el tribunal competente dictará una resolución designando a los Veedores titular y suplente nominados en la forma establecida en el artículo 22. En la misma resolución dispondrá lo siguiente:

1) Que durante el plazo de treinta días contado desde la notificación de esta resolución, prorrogable de conformidad a lo dispuesto en el artículo 58, el Deudor gozará de una Protección Financiera Concursal en virtud de la cual:

a) No podrá declararse ni iniciarse en contra del Deudor un Procedimiento Concursal de Liquidación, ni podrán iniciarse en su contra juicios ejecutivos, ejecuciones de cualquier clase o restituciones en juicios de arrendamiento. Lo anterior no se aplicará a los juicios laborales sobre obligaciones que gocen de preferencia de primera clase, suspendiéndose en este caso sólo la ejecución y realización de bienes del Deudor, salvo que se trate de juicios laborales de este tipo que el Deudor tuviere en tal carácter a favor de su cónyuge, de sus parientes, o de los gerentes, administradores, apoderados con poder general de administración u otras personas que tengan injerencia en la administración de sus negocios. Para estos efectos, se entenderá por parientes del Deudor o de sus representantes legales los ascendientes, descendientes, y los colaterales hasta el cuarto grado de consanguinidad y afinidad, inclusive.

b) Se suspenderá la tramitación de los procedimientos señalados en la letra a) precedente y los plazos de prescripción extintiva.

c) Todos los contratos suscritos por el Deudor mantendrán su vigencia y condiciones de pago. En consecuencia, no podrán terminarse anticipadamente en forma unilateral, exigirse anticipadamente su cumplimiento o hacerse efectivas las garantías contratadas, invocando como causal el inicio de un Procedimiento Concursal de Reorganización. El crédito del acreedor que contraviniere esta 52
prohibición quedará pospuesto hasta que se pague a la totalidad de los acreedores a quienes les afectare el Acuerdo de Reorganización Judicial, incluidos los acreedores Personas Relacionadas del Deudor.

Para hacer efectiva la postergación señalada en el inciso anterior, deberá solicitarse su declaración en forma incidental ante el tribunal que conoce del Procedimiento Concursal de Reorganización.

d) Si el Deudor formare parte de algún registro público como contratista o prestador de cualquier servicio, y siempre que se encuentre al día en sus obligaciones contractuales con el respectivo mandante, no podrá ser eliminado ni se le privará de participar en procesos de licitación fundado en el inicio de un Procedimiento Concursal de Reorganización. Si la entidad pública lo elimina de sus registros o discrimina su participación, fundado en la apertura de un Procedimiento Concursal de Reorganización, a pesar de encontrarse al día en sus obligaciones con el respectivo mandante, deberá indemnizar los perjuicios que dicha discriminación o eliminación le provoquen al Deudor.

2) Que durante la Protección Financiera Concursal se aplicarán al Deudor las siguientes medidas cautelares y de restricción:

a) Quedará sujeto a la intervención del Veedor titular designado en la misma resolución, el que tendrá los deberes contenidos en el artículo 25;

b) No podrá gravar o enajenar sus bienes, salvo aquellos cuya enajenación o venta sea propia de su giro o que resulten estrictamente necesarios para el normal desenvolvimiento de su actividad; y respecto de los demás bienes o activos, se estará a lo previsto en el artículo 74, y

c) Tratándose de personas jurídicas, éstas no podrán modificar sus pactos, estatutos sociales o régimen de poderes. La inscripción de cualquier transferencia de acciones de la Empresa Deudora en los registros sociales pertinentes requerirá la autorización del Veedor, que la extenderá en la medida que ella no altere o afecte los derechos de los acreedores. Lo anterior no regirá respecto de las sociedades anónimas abiertas que hagan oferta pública de sus valores.

3) La fecha en que expirará la Protección Financiera Concursal.

4) La orden al Deudor para que a través del Veedor publique en el Boletín Concursal y acompañe al tribunal competente, a lo menos diez días antes de la fecha fijada para la Junta de Acreedores, su propuesta de Acuerdo de Reorganización Judicial. Si el Deudor no da cumplimiento a esta orden, el Veedor certificará esta circunstancia y el tribunal competente dictará la Resolución de Liquidación, sin más trámite.

5) La fecha, lugar y hora en que deberá efectuarse la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo de Reorganización Judicial que presente el Deudor. La fecha de dicha Junta será aquella en la que expire la Protección Financiera Concursal.

6) Que dentro de quince días contados desde la notificación de esta resolución, todos los acreedores deberán acreditar ante el tribunal competente su personería para actuar en el Procedimiento Concursal de Reorganización, con indicación expresa de la facultad que le confieren a sus apoderados para conocer, modificar y adoptar el Acuerdo de Reorganización Judicial.

7) La orden para que el Veedor inscriba copia de esta resolución en los conservadores de bienes raíces correspondientes al margen de la inscripción de propiedad de cada uno de los inmuebles que pertenecen al deudor.

8) La orden al Veedor para que acompañe al tribunal competente y publique en el Boletín Concursal su informe sobre la propuesta de Acuerdo de Reorganización Judicial, a lo menos tres días antes de la fecha fijada para la celebración de la Junta de Acreedores que votará dicho acuerdo. Este Informe del Veedor deberá contener la calificación fundada acerca de:

a) Si la propuesta es susceptible de ser cumplida, habida consideración de las condiciones del Deudor;

b) El monto probable de recuperación que le correspondería a cada acreedor en sus respectivas categorías, en caso de un Procedimiento Concursal de Liquidación, y

c) Si la propuesta de determinación de los créditos y su preferencia indicada por el Deudor se ajustan a la ley.

Si el Veedor no presentare el referido informe dentro del plazo indicado, el Deudor, cualquiera de los acreedores o el tribunal competente informará a la Superintendencia para que se apliquen las sanciones pertinentes. En este caso, el Acuerdo de Reorganización Judicial se votará con prescindencia del Informe del Veedor.

9) Que dentro de quinto día de efectuada la notificación de esta resolución, deberán asistir a una audiencia el Deudor y los tres mayores acreedores indicados en la certificación del contador auditor independiente referida en el artículo 55. Esta diligencia se efectuará con los que concurran y tratará sobre la proposición de honorarios que formule el Veedor. Si en ella no se arribare a acuerdo sobre el monto de los honorarios y su forma de pago, o no asistiere ninguno de los citados, dichos honorarios se fijarán por el tribunal competente sin ulterior recurso.

10) La orden al Deudor para que proporcione al Veedor copia de todos los antecedentes acompañados conforme al artículo 56. Estos antecedentes y la copia de la resolución de que trata este artículo serán publicados por el Veedor en el Boletín Concursal dentro del plazo de tres días contado desde su dictación.

##### Artículo 58.- Prórroga de la Protección Financiera Concursal. {-}

El plazo establecido en el número 1) del artículo anterior para la Protección Financiera Concursal podrá prorrogarse hasta por treinta días, si el Deudor obtiene el apoyo de dos o más acreedores, que representen más del 30% del total del pasivo, excluidos los créditos de las Personas Relacionadas con el Deudor. Hasta el décimo día anterior al vencimiento del plazo antes señalado, el Deudor podrá solicitar una nueva prórroga por otros treinta días si obtiene el apoyo de dos o más acreedores que representen más del 50% del total del pasivo, excluidos los créditos de las Personas Relacionadas con el Deudor.

Sin perjuicio de lo anterior, se podrá solicitar en un solo acto la prórroga del plazo regulado para la Protección Financiera Concursal a que se refiere el número 1) del artículo anterior hasta por sesenta días, si el Deudor obtiene el apoyo de dos o más acreedores que representen más del 50% del total del pasivo, excluidos los créditos de las Personas Relacionadas con el Deudor.

Los acreedores hipotecarios y prendarios que presten su apoyo para la prórroga de la Protección Financiera Concursal no perderán su preferencia y podrán impetrar las medidas conservativas que procedan.

##### Artículo 59.- Nueva fecha y hora de la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo de Reorganización Judicial. {-}

Para lograr la prórroga regulada en el artículo anterior, el Deudor deberá presentar al tribunal competente, junto con la respectiva solicitud de prórroga, las cartas de apoyo de los acreedores autorizadas ante un ministro de fe, y un certificado extendido por un contador auditor independiente al Deudor, que indique los porcentajes del pasivo que permitan el apoyo requerido.
Acogida la prórroga de la Protección Financiera Concursal, el tribunal competente deberá fijar la nueva fecha y hora de la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo de Reorganización Judicial.

#### Párrafo 1. Del objeto de la propuesta del Acuerdo de Reorganización Judicial {-}

##### Artículo 60.- Objeto de la propuesta de Acuerdo de Reorganización Judicial. {-}

La propuesta podrá versar sobre cualquier objeto tendiente a reestructurar los pasivos y activos de una Empresa Deudora.

##### Artículo 61.- Acuerdos de Reorganización Judicial por clases o categorías de acreedores. {-}

La propuesta de Acuerdo podrá separarse en clases o categorías de acreedores y se podrá formular una propuesta para los acreedores valistas y otra para los acreedores hipotecarios y prendarios cuyos créditos se encuentren garantizados con bienes de propiedad del Deudor o de terceros. Los acreedores hipotecarios y prendarios que voten la propuesta del Acuerdo conservarán sus preferencias.

La propuesta de Acuerdo será igualitaria para todos los acreedores de una misma clase o categoría, salvo que medie acuerdo en contrario, de conformidad a lo dispuesto en los artículos 64 y siguientes.

Los acreedores hipotecarios y prendarios cuyos créditos se encuentren garantizados con bienes de propiedad del Deudor o de terceros podrán votar la propuesta de Acuerdo que se formule para acreedores valistas si renuncian a la preferencia de sus créditos y no podrán votar la propuesta de Acuerdo que se formule para la clase o categoría de los acreedores hipotecarios o prendarios, salvo que dicha renuncia sea parcial y se manifieste expresamente.

Si los acreedores hipotecarios y prendarios votan la propuesta de Acuerdo de los acreedores valistas, los montos de sus créditos preferentes se descontarán del pasivo de su clase o categoría y se incluirán en el pasivo de la clase o categoría de los acreedores valistas para efectos del cómputo a que se refiere el artículo 79 por las sumas a que hubiere alcanzado la renuncia.

##### Artículo 62.- Propuestas alternativas de Acuerdo de Reorganización Judicial. {-}

En cada una de sus clases o categorías, la propuesta de Acuerdo podrá contener una proposición principal y otras alternativas para todos los acreedores de la misma clase o categoría, en cuyo caso éstos deberán optar por regirse por alguna de ellas, dentro de los diez días siguientes a la fecha de la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo.

##### Artículo 63.- Posposición del pago a acreedores Personas Relacionadas. {-}

Los acreedores Personas Relacionadas con el Deudor, cuyos créditos no se encuentren debidamente documentados 90 días antes del inicio del Procedimiento Concursal de Reorganización, quedarán pospuestos en el pago de sus créditos, hasta que se paguen íntegramente los créditos de los demás acreedores a los que les afectará el Acuerdo de Reorganización Judicial. Sin perjuicio de lo anterior, el Acuerdo podrá hacer aplicable la referida posposición a otros acreedores Personas Relacionadas con el Deudor, cuyos créditos se encuentren debidamente documentados, previo informe fundado del Veedor. Esta posposición no regirá respecto de los créditos que se originen en virtud de los artículos 72 y 73.

Tampoco regirá respecto de los créditos que se originen en virtud del artículo 74, en la medida que se autorice por los acreedores que representen más del 50% del pasivo del Deudor.

##### Artículo 64.- Diferencias entre acreedores de igual clase o categoría. {-}

En las propuestas de Acuerdo de Reorganización Judicial se podrán establecer condiciones más favorables para algunos de los acreedores de una misma clase o categoría, siempre que los demás acreedores de la respectiva clase o categoría lo acuerden con Quórum Especial, el cual se calculará únicamente sobre el monto de los créditos de estos últimos.

##### Artículo 65.- Constitución de garantías en los Acuerdos de Reorganización Judicial. {-}

En los Acuerdos podrá estipularse la constitución de garantías para asegurar el cumplimiento de las obligaciones del Deudor. Estas garantías podrán constituirse en el mismo Acuerdo o en instrumentos separados.

Para estos efectos, los acreedores podrán designar a uno o más de ellos para que los representen en la celebración de los actos que sean necesarios para la debida constitución de las garantías.

##### Artículo 66.- Acreedores comprendidos en los Acuerdos de Reorganización Judicial. {-}

Los Acuerdos sólo afectarán a los acreedores cuyos créditos se originen con anterioridad a la Resolución de Reorganización regulada en el artículo 57.
Los créditos que se originen con posterioridad no serán incluidos en el Acuerdo de Reorganización Judicial.

##### Artículo 67.- Prohibición de repartos. {-}

Se prohíbe a la Empresa Deudora repartir sumas a sus accionistas o socios, bajo ningún concepto, ni directa ni indirectamente, sea por la vía de reducción de capital, condonación de préstamos otorgados y/o repartos de dividendos antes de haber pagado el 100% de las obligaciones emanadas del Acuerdo de Reorganización Judicial, salvo que los acreedores expresamente lo autoricen en la forma que lo determine el Acuerdo.

##### Artículo 68.- Cláusula arbitral en Acuerdos de Reorganización Judicial. {-}

En cualquiera de las clases o categorías de un Acuerdo de Reorganización Judicial podrá estipularse una cláusula arbitral, en cuyo caso las diferencias que se produzcan entre el Deudor y uno o más acreedores o entre éstos, con motivo de la aplicación, interpretación, cumplimiento, terminación o declaración de incumplimiento del Acuerdo, se someterán a arbitraje. Éste será obligatorio para todos los acreedores a los que afecte el referido Acuerdo.
Si el árbitro declara la terminación o el incumplimiento del Acuerdo, remitirá de inmediato el expediente al tribunal competente para que éste dicte la Resolución de Liquidación en conformidad a esta ley.

##### Artículo 69.- Interventor y Comisión de Acreedores. {-}

El Acuerdo de Reorganización Judicial deberá estipular el nombramiento de un interventor por al menos un año contado desde el Acuerdo, el que recaerá en un Veedor vigente de la Nómina de Veedores. El interventor nombrado tendrá las atribuciones, deberes y remuneración que el mismo Acuerdo señale. Si ellas no se especifican, se entenderá que tendrá las señaladas en el artículo 294 del Código de Procedimiento Civil.

El Veedor tendrá la obligación de poner en conocimiento, de forma fundada, el incumplimiento del Acuerdo a la Superintendencia y a los acreedores que les afecte, mediante notificación por Correo Electrónico.

Sin perjuicio de lo anterior, en el Acuerdo de Reorganización Judicial podrá designarse a una Comisión de Acreedores para supervigilar el cumplimiento de sus estipulaciones, con las atribuciones, deberes y remuneración que, en su caso, señale el Acuerdo.

#### Párrafo 2. De la determinación del pasivo {-}

##### Artículo 70.- Verificación y objeción de los créditos. {-}

Los acreedores tendrán un plazo de ocho días contado desde la notificación de la Resolución de Reorganización a que se refiere el artículo 57 para verificar sus créditos ante el tribunal que conoce del procedimiento. Con tal propósito, deberán acompañar los títulos justificativos de éstos, señalando, en su caso, si se encuentran garantizados con prenda o hipoteca y el avalúo comercial de los bienes sobre los que recaen las garantías. No será necesaria verificación alguna si los créditos y el avalúo comercial de las garantías se encontraren señaladas, a satisfacción del acreedor, en el estado de deudas a que se refiere el número 4) del artículo 56 publicado en el Boletín Concursal.

Vencido el plazo señalado en el inciso anterior y dentro de los dos días siguientes, el Veedor publicará en el Boletín Concursal todas las verificaciones presentadas, indicando los créditos que se encuentren garantizados con prenda o hipoteca y el avalúo comercial de los bienes sobre los que recaen las garantías.

En el plazo de ocho días siguientes a la publicación indicada en el inciso precedente, el Veedor, el Deudor y los acreedores podrán deducir objeción fundada sobre la falta de títulos justificativos de los créditos, sus montos, preferencias o sobre el avalúo comercial de los bienes sobre los que recaen las garantías, que se indican en el estado de deudas que presenta el Deudor, de conformidad al número 4) del artículo 56 o en las verificaciones presentadas por los acreedores.

Los interesados presentarán sus objeciones ante el tribunal. Vencido el plazo indicado en el inciso precedente, y dentro de los dos días siguientes, el Veedor publicará en el Boletín Concursal todas las objeciones presentadas. Asimismo, expirado el plazo que se señala en el citado inciso anterior sin que se formulen objeciones, los créditos y el avalúo comercial de los bienes sobre los que recaen las garantías no objetados, quedarán reconocidos.

El Veedor confeccionará la nómina de los créditos reconocidos, la que deberá indicar los montos de los créditos, si éstos se encuentran garantizados con prenda o hipoteca y el avalúo comercial de los bienes sobre los que recaen las garantías, acompañándola al expediente dentro de quinto día de expirado el plazo para objetar y la publicará en el Boletín Concursal, sirviendo ésta como única nómina para la votación a que se refiere el artículo 78, sin perjuicio de su posterior ampliación o modificación de acuerdo al artículo siguiente.

##### Artículo 71.- Impugnación de créditos. {-}

Si se formulan objeciones, el Veedor arbitrará las medidas necesarias para subsanarlas. Si no se subsanan, los créditos y el avalúo comercial de los bienes sobre los que recaen las garantías que fueren objeto de dichas objeciones se considerarán impugnados, y el Veedor los acumulará, emitirá un informe acerca de si existen o no fundamentos plausibles para ser considerados por el tribunal competente, y se pronunciará fundadamente sobre el avalúo comercial del bien sobre el que recae la garantía objetada.

El Veedor acompañará al tribunal competente la nómina de créditos impugnados con su respectivo informe y la nómina de créditos reconocidos indicada en el artículo 70, y las publicará en Boletín Concursal dentro de los cinco días siguientes a la expiración del plazo previsto para objetar que se señala en el inciso primero del artículo anterior.

Agregados al expediente los antecedentes que señala el inciso anterior, el tribunal citará a una audiencia única y verbal para el fallo de las impugnaciones. Dicha audiencia se celebrará dentro de tercero día contado desde la notificación de la resolución que tiene por acompañada la nómina de créditos reconocidos e impugnados.

A la audiencia podrán concurrir el Veedor, el Deudor, los impugnantes y los impugnados. En ésta deberán resolverse las incidencias que promuevan las partes en relación a las impugnaciones. El tribunal competente podrá, si fuere estrictamente necesario, suspender y continuar la referida audiencia con posterioridad. Con todo, la resolución que se pronuncie sobre las impugnaciones deberá dictarse a más tardar el segundo día anterior a la fecha de celebración de la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo.

La resolución que falle las impugnaciones ordenará la incorporación o modificación de créditos en la nómina de créditos reconocidos, o la modificación del avalúo comercial de los bienes sobre los que recaen las garantías, cuando corresponda, y será apelable en el sólo efecto devolutivo. El Veedor deberá publicar la nómina de créditos reconocidos según la resolución anterior en el Boletín Concursal, a más tardar el día anterior a la fecha de celebración de la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo.

#### Párrafo 3. De la continuidad del suministro, de la venta de activos y de los nuevos recursos durante la Protección Financiera Concursal {-}

##### Artículo 72.- Continuidad del suministro. {-}

Los proveedores de bienes y servicios que sean necesarios para el funcionamiento de la Empresa Deudora, cuyas facturas tengan como fecha de emisión no menos de ocho días anteriores a la fecha de la Resolución de Reorganización y en la medida que en su conjunto no superen el 20% del pasivo señalado en la certificación contable referida en el artículo 55, se pagarán preferentemente en las fechas originalmente convenidas, siempre que el respectivo proveedor mantenga el suministro a la Empresa Deudora, circunstancia que deberá acreditar el Veedor.

En caso de no suscribirse el Acuerdo y, en consecuencia, se dictare la Resolución de Liquidación de la Empresa Deudora, los créditos provenientes de este suministro se pagarán con la preferencia establecida en el número 4 del artículo 2472 del Código Civil.

##### Artículo 73.- Operaciones de comercio exterior. {-}

Los que financien operaciones de comercio exterior de la Empresa Deudora se pagarán preferentemente en las fechas originalmente convenidas, siempre que esos acreedores mantengan las líneas de financiamiento u otorguen nuevos créditos para este tipo de operaciones, circunstancia que deberá acreditar el Veedor.

En caso que no se suscribiere el Acuerdo de Reorganización Judicial y, en consecuencia, se dictare la Resolución de Liquidación de la Empresa Deudora, los créditos provenientes de estas operaciones de comercio exterior se pagarán con la preferencia establecida en el número 4 del artículo 2472 del Código Civil.

##### Artículo 74.- Venta de activos y contratación de préstamos durante la Protección Financiera Concursal. {-}

Durante la Protección Financiera Concursal, la Empresa Deudora podrá vender o enajenar activos cuyo valor no exceda el 20% de su activo fijo contable, y podrá adquirir préstamos para el financiamiento de sus operaciones, siempre que éstos no superen el 20% de su pasivo señalado en la certificación contable referida en el artículo 55.

La venta, enajenación o contratación de préstamos que excedan los montos señalados en el inciso anterior, así como toda operación con Personas Relacionadas con la Empresa Deudora, requerirá la autorización de los acreedores que representen más del 50% del pasivo del Deudor.

Los préstamos contratados por la Empresa Deudora en virtud de este artículo no se considerarán en las nóminas de créditos y se pagarán preferentemente en las fechas convenidas, siempre que se utilicen para el financiamiento de sus operaciones, circunstancia que deberá acreditar el Veedor.

En caso de no suscribirse el Acuerdo y, en consecuencia, se dictare la Resolución de Liquidación de la Empresa Deudora, estos préstamos se pagarán con la preferencia establecida en el número 4 del artículo 2472 del Código Civil.

##### Artículo 75.- Venta de bienes otorgados en prenda o hipoteca durante la Protección Financiera Concursal. {-}

En caso que no se acuerde la reorganización y se declare la liquidación de la Empresa Deudora, el acreedor prendario o hipotecario que autorice la enajenación de los bienes otorgados en prenda o hipoteca cuyo valor comercial exceda el monto del respectivo crédito garantizado, podrá percibir de la venta el monto de su respectivo crédito. Lo anterior procederá siempre que se garantice el pago de los créditos de primera clase, mediante el otorgamiento de cualquier instrumento de garantía que reconozcan las leyes vigentes o que la Superintendencia autorice mediante una norma de carácter general.

##### Artículo 76.- Valorización de activos y fiscalización de recursos. {-}

Para efectos de determinar el valor de los activos a vender o enajenar, se estará a la valorización que realice el Veedor.

El Veedor verificará que el producto de todos los actos o contratos que se otorguen o suscriban con motivo de las operaciones que se regulan en el presente Párrafo, ingrese efectivamente a la caja de la Empresa Deudora y se destine única y exclusivamente a financiar su giro. A estos actos o contratos no les será aplicable lo dispuesto en el Capítulo VI de esta ley.

### Título 2. De la propuesta de Acuerdo de Reorganización Judicial {-}

#### Párrafo 1. De las normas generales {-}

##### Artículo 77.- Efectos del retiro del Acuerdo. {-}

Una vez notificada la propuesta de Acuerdo, ésta no podrá ser retirada por el Deudor, salvo que cuente con el apoyo de acreedores que representen a lo menos el 75% del pasivo.

Si la propuesta de Acuerdo es retirada por el Deudor sin contar con el apoyo referido en el inciso anterior, el tribunal competente dictará la Resolución de Liquidación.

##### Artículo 78.- Acreedores con derecho a voto. {-}

Sólo tienen derecho a concurrir y votar los acreedores cuyos créditos se encuentren en la nómina de créditos reconocidos a que se refiere el artículo 70 y aquellos que figuren en la ampliación de esta nómina, de acuerdo a lo previsto en el artículo 71. En ambos casos deberá darse cumplimiento a lo ordenado en el número 6) del artículo 57, relativo a la acreditación de personerías.

Los acreedores cuyos créditos se encuentren garantizados con prenda o hipoteca votarán de acuerdo al avalúo comercial de los bienes sobre los que recaen las garantías, conforme conste en la nómina de créditos reconocidos y en su ampliación o modificación, en su caso.

Cuando el avalúo comercial de los bienes sobre los que recaen las garantías exceda el valor del crédito que garantizan, el acreedor correspondiente votará de acuerdo al monto de su crédito, según conste en la nómina de créditos reconocidos y en su ampliación o modificación, en su caso.

##### Artículo 79.- Acuerdo de la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta. {-}

Cada una de las clases o categorías de propuestas de Acuerdo que establece el artículo 61 será analizada, deliberada y acordada en forma separada en la misma junta, pudiendo proponerse modificaciones, sin perjuicio de lo previsto en el artículo 82.

La propuesta se entenderá acordada cuando cuente con el consentimiento del Deudor y el voto conforme de los dos tercios o más de los acreedores presentes, que representen al menos dos tercios del total del pasivo con derecho a voto correspondiente a su respectiva clase o categoría.

No podrán votar las Personas Relacionadas con el Deudor y sus créditos no se considerarán en el pasivo.

Los cesionarios de créditos adquiridos dentro de los treinta días anteriores a la fecha de inicio del Procedimiento Concursal de Reorganización, conforme se indica en el artículo 54, no podrán concurrir a la Junta de Acreedores para deliberar y votar el Acuerdo y tampoco podrán impugnarlo.

El acuerdo sobre la propuesta de una clase o categoría se adoptará bajo la condición suspensiva de que se acuerde la propuesta de la otra clase o categoría en la misma Junta de Acreedores, o en la que se realice de conformidad a lo previsto en el artículo 82.

##### Artículo 80.- Procedimiento de registro de firmas. {-}

Para obtener las mayorías que exige el Procedimiento Concursal de Reorganización, el Veedor podrá recabar la votación de cualquier acreedor, mediante la suscripción de uno o más documentos ante un ministro de fe o mediante firma electrónica avanzada, en que conste la aceptación de los acreedores.

Los votos que se obtengan mediante este sistema se considerarán como votos de acreedores presentes en la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo, para los efectos del cómputo de las mayorías.

Los acreedores del Deudor podrán suscribir estos documentos desde la publicación de la propuesta de Acuerdo en el Boletín Concursal, y hasta tres días antes de la fecha fijada para la Junta de Acreedores llamada a conocer y pronunciarse sobre dicha propuesta.

##### Artículo 81.- Ausencia del Deudor en la Junta de Acreedores. {-}

Si el Deudor no compareciere a la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo, el tribunal competente deberá dictar la Resolución de Liquidación en la misma Junta.

##### Artículo 82.- Suspensión de la Junta de Acreedores. {-}

La Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo podrá acordar con, Quórum Calificado, su suspensión por no más diez días, fijando al efecto nuevo día y hora para su reanudación.

El Deudor conservará la Protección Financiera Concursal hasta la celebración de dicha Junta.

##### Artículo 83.- Modificación del Acuerdo. {-}

Las modificaciones al Acuerdo deberán adoptarse por el Deudor y los acreedores que lo suscribieron agrupados en sus respectivas clases o categorías, conforme al mismo procedimiento y mayorías exigidas en el artículo 79.

No obstante lo anterior, el Acuerdo que establezca la constitución de una Comisión de Acreedores podrá facultarla para modificarlo con el quórum de aprobación que el mismo Acuerdo determine, el que en ningún caso podrá ser inferior al Quórum Simple.

La modificación podrá recaer sobre todo o parte del contenido del Acuerdo, salvo lo referente a la calidad de acreedor, su clase o categoría, diferencias entre acreedores de igual clase o categoría, monto de sus créditos, sus preferencias, y respecto de aquellas materias que el Acuerdo determine como no modificables por la Comisión de Acreedores.

En las Juntas de Acreedores que se celebren con posterioridad a la aprobación del Acuerdo por el tribunal, el derecho a voto se determinará en conformidad al artículo 78. No tendrán derecho a voto los acreedores que tengan la calidad de Personas Relacionadas con el Deudor.

##### Artículo 84.- Notificación del Acuerdo. {-}

El texto íntegro del Acuerdo con sus modificaciones, en su caso, será notificado por el Veedor en el Boletín Concursal.

#### Párrafo 2. De la impugnación del Acuerdo de Reorganización Judicial {-}

##### Artículo 85.- Causales para impugnar el Acuerdo. {-}

El Acuerdo podrá ser impugnado por los acreedores a los que les afecte, siempre que se funde en alguna de las siguientes causales:

1) Defectos en las formas establecidas para la convocatoria y celebración de la junta de acreedores, que hubieren impedido el ejercicio de los derechos de los acreedores o del deudor.

2) El error en el cómputo de las mayorías requeridas en este Capítulo, siempre que incida sustancialmente en el quórum del Acuerdo de Reorganización Judicial.

3) Falsedad o exageración del crédito o incapacidad o falta de personería para votar de alguno de los acreedores que hayan concurrido con su voto a formar el quórum necesario para el Acuerdo, si excluido este acreedor o la parte falsa o exagerada del crédito, no se logra el quórum del Acuerdo.

4) Acuerdo entre uno o más acreedores y el Deudor para votar a favor, abstenerse de votar o rechazar el Acuerdo, para obtener una ventaja indebida respecto de los demás acreedores.

5) Ocultación o exageración del activo o pasivo.

6) Por contener una o más estipulaciones contrarias a lo dispuesto en esta ley.

##### Artículo 86.- Plazo para impugnar el Acuerdo. {-}

Podrá impugnarse el Acuerdo dentro del plazo de cinco días contado desde su publicación en el Boletín Concursal.

Las impugnaciones presentadas fuera de plazo serán rechazadas de plano.

##### Artículo 87.- Audiencia única de resolución de impugnaciones. {-}

Las impugnaciones al Acuerdo se tramitarán como un solo incidente y se fallarán conjuntamente en una audiencia única, que el tribunal competente citará para tal efecto, dentro de los diez días de vencido el plazo para impugnar. Esta audiencia será verbal y se llevará a cabo con los que asistan. En la misma audiencia deberán resolverse las incidencias que promuevan las partes. El tribunal podrá, si así lo estima, suspender y continuar la referida audiencia con posterioridad. La resolución que se pronuncie sobre las impugnaciones al Acuerdo deberá dictarse a más tardar dentro de los treinta días siguientes a la fecha de celebración de la referida audiencia.

La resolución que resuelva las impugnaciones se publicará en el Boletín Concursal. Esta resolución será apelable en el solo efecto devolutivo.

##### Artículo 88.- Nueva propuesta de Acuerdo. {-}

Si se acoge por resolución firme y ejecutoriada la impugnación al Acuerdo por las causales establecidas en los números 1), 2), 3) y 6) del artículo 85, el Deudor podrá presentar una nueva propuesta de Acuerdo, dentro de los diez días siguientes contados desde que se notifique la resolución que tuvo por acogida la impugnación referida, siempre que esta nueva propuesta se presente apoyada por dos o más acreedores que representen, a lo menos, un 66% del pasivo total con derecho a voto. En este caso, el Deudor gozará de Protección Financiera Concursal hasta la celebración de la Junta llamada a conocer y pronunciarse sobre la nueva propuesta. La resolución que tenga por presentada la nueva propuesta de Acuerdo fijará la fecha de la Junta de Acreedores llamada a conocer y pronunciarse sobre dicha nueva propuesta, la que deberá celebrarse dentro de los diez días siguientes contados desde que el Deudor la presentó.

Si el Deudor no presentare la nueva propuesta de Acuerdo que reúna las condiciones indicadas en el inciso anterior, dentro del plazo antes establecido, el tribunal competente dictará, de oficio y sin más trámite, la Resolución de Liquidación de la Empresa Deudora.

Si se acoge una impugnación al Acuerdo por las causales establecidas en los números 4) y 5) del artículo 85, el tribunal, de oficio y sin más trámite, ordenará el inicio del Procedimiento Concursal de Liquidación en la misma resolución que acoge la impugnación, y el Deudor no podrá presentar nuevamente una propuesta de Acuerdo.

#### Párrafo 3. De la aprobación y vigencia del Acuerdo de Reorganización Judicial {-}

##### Artículo 89.- Aprobación y vigencia del Acuerdo. {-}

El Acuerdo se entenderá aprobado y comenzará a regir una vez vencido el plazo para impugnarlo, sin que se hubiere impugnado y el tribunal competente lo declare así de oficio o a petición de cualquier interesado o del Veedor.
Si el Acuerdo fuere impugnado y las impugnaciones fueren desechadas, el tribunal competente lo declarará aprobado en la resolución que deseche la o las impugnaciones, y aquél comenzará a regir desde que dicha resolución cause ejecutoria.

Las resoluciones señaladas en los incisos primero y segundo de este artículo se notificarán en el Boletín Concursal.

El Acuerdo regirá no obstante las impugnaciones que se hubieren interpuesto en su contra. Sin embargo, si éstas fueren interpuestas por acreedores de una determinada clase o categoría, que representen en su conjunto a lo menos el 30% del pasivo con derecho a voto de su respectiva clase o categoría, el Acuerdo no empezará regir hasta que dichas impugnaciones fueren desestimadas por sentencia firme y ejecutoriada. En este caso y en el del inciso segundo de este artículo, los actos y contratos ejecutados o celebrados por el Deudor en el tiempo que medie entre el Acuerdo y la fecha en que quede ejecutoriada la resolución que acoja las impugnaciones, no podrán dejarse sin efecto.

El recurso de casación deducido en contra de la resolución de segunda instancia que desecha la o las impugnaciones, no suspenderá el cumplimiento de dicha resolución, incluso si la parte vencida solicita que se otorgue fianza de resultas por la parte vencedora.

Si se acogen las impugnaciones al Acuerdo por resolución firme y ejecutoriada, las obligaciones y derechos existentes entre el Deudor y sus acreedores con anterioridad a éste se regirán por sus respectivas convenciones.

##### Artículo 90.- Autorización del Acuerdo. {-}

Una copia del acta de la Junta de Acreedores en la que conste el voto favorable del Acuerdo y su texto íntegro, junto a la copia de la resolución judicial que lo aprueba y su certificado de ejecutoria, podrá ser autorizada por un ministro de fe o protocolizarse ante un notario público. Una vez autorizada o protocolizada, tendrá mérito ejecutivo para todos los efectos legales.

#### Párrafo 4. De los efectos del Acuerdo de Reorganización Judicial {-}

##### Artículo 91.- Efectos. {-}

El Acuerdo, debidamente aprobado, obliga al Deudor y a todos los acreedores de cada clase o categoría de éste, hayan o no concurrido a la Junta que lo acuerde.

##### Artículo 92.- Cancelación de anotaciones e inscripciones. {-}

Aprobado el Acuerdo de Reorganización Judicial, se cancelarán las inscripciones previstas en el número 7) del artículo 57.

##### Artículo 93.- Efectos sobre los créditos. {-}

Los créditos que sean parte del Acuerdo de Reorganización Judicial se entenderán remitidos, novados o repactados, según corresponda, para todos los efectos legales.

El acreedor, contribuyente del impuesto de primera categoría de la Ley sobre Impuesto a la Renta, contenida en el artículo 1° del decreto ley N° 824, de 1974, podrá deducir como gasto necesario conforme a lo dispuesto en el número 4° del artículo 31 de dicha ley, las cantidades que correspondan a la condonación o remisión de deudas, intereses, reajustes u otras cantidades que se hayan devengado en su favor, siempre y cuando cumpla con las siguientes condiciones copulativas:

1) Que se trate de créditos otorgados o adquiridos con anterioridad al plazo de un año contado desde la celebración del Acuerdo de Reorganización Judicial;

2) Que dicha condonación o remisión conste detalladamente en el referido Acuerdo o sus modificaciones, aprobado conforme al artículo 89, y

3) Que no correspondan a créditos de Personas Relacionadas con el Deudor ni a créditos de acreedores Personas Relacionadas entre sí, cuando éstos, en su conjunto, representen el 50% o más del pasivo reconocido con derecho a voto.

Lo anterior, es sin perjuicio de la obligación del Deudor de reconocer como ingreso, para efectos tributarios, aquellas cantidades que se hubieren devengado a favor del acreedor y que se condonen o remitan.

##### Artículo 94.- De los bienes no esenciales para la continuidad del giro de la Empresa Deudora. {-}

En el plazo de ocho días siguientes a la publicación de la Resolución de Reorganización referida en el artículo 57, el acreedor cuyo crédito se encuentre garantizado con prenda o hipoteca podrá solicitar fundadamente al tribunal competente que declare que el bien sobre el que recae su garantía no es esencial para el giro de la Empresa Deudora. Para resolver lo anterior, el tribunal podrá solicitar al Veedor un informe que contendrá la calificación de si el bien es o no esencial para el giro de la Empresa Deudora y el avalúo comercial del bien sobre el que recaen las referidas garantías. El tribunal deberá resolver dicha calificación en única instancia, a más tardar el segundo día anterior a la fecha de celebración de la Junta de Acreedores llamada a conocer y pronunciarse sobre las proposiciones de Acuerdo de Reorganización Judicial.

El acreedor cuya garantía recae sobre un bien calificado como no esencial concurrirá y votará en la clase o categoría de acreedores valistas, únicamente por el saldo del crédito no cubierto por la garantía. El saldo cubierto por la garantía no se considerará en el pasivo de la clase o categoría de acreedores garantizados.

El acreedor cuyo crédito no hubiere sido enteramente cubierto por la garantía podrá solicitar, mediante un procedimiento incidental ante el mismo tribunal que conoció y se pronunció sobre el Acuerdo, que dicho Acuerdo se cumpla a su favor, mientras no se encuentren prescritas las acciones que del mismo emanen.

El excedente que resulte de la venta del bien declarado no esencial, una vez pagado el respectivo crédito, se destinará al cumplimiento del Acuerdo.

##### Artículo 95.- Efectos del Acuerdo de Reorganización Judicial en las obligaciones garantizadas del Deudor. {-}

Tales efectos serán los siguientes:

1. Respecto de las obligaciones del Deudor garantizadas con prenda o hipoteca sobre bienes de propiedad del Deudor o de terceros, declarados esenciales para el giro de la Empresa Deudora, de acuerdo a los artículos 56 y 94, se aplicarán los términos y modalidades establecidos en el Acuerdo de Reorganización Judicial.

2. Respecto de las obligaciones del Deudor garantizadas con prenda o hipoteca sobre bienes de propiedad del Deudor, declarados no esenciales para el giro de la Empresa Deudora de acuerdo a los artículos 56 y 94, regirá lo establecido en los incisos segundo y tercero del artículo anterior.

3. Respecto de las obligaciones del Deudor garantizadas con prenda o hipoteca sobre bienes de propiedad de terceros, declarados no esenciales para el giro de la Empresa Deudora de acuerdo a los artículos 56 y 94, deberá distinguirse:

a) Si el respectivo acreedor vota a favor del Acuerdo, se sujetará a los términos y modalidades establecidos en el referido acuerdo y no podrá perseguir su crédito en términos distintos a los estipulados.

b) Si el respectivo acreedor manifiesta su intención de no votar o no asiste a la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo, su crédito no se considerará en el pasivo con derecho a voto correspondiente a su clase o categoría, y podrá cobrar su crédito respecto de las prendas o hipotecas otorgadas por terceros.

4. Respecto de las obligaciones del Deudor garantizadas con cauciones personales, deberá distinguirse:

a) Si el respectivo acreedor vota en su clase o categoría de valista a favor del Acuerdo, se sujetará a los términos y modalidades establecidos en el referido acuerdo y no podrá cobrar su crédito en términos distintos a los estipulados.

b) Si el respectivo acreedor manifiesta su intención de no votar o no asiste a la Junta de Acreedores llamada a conocer y pronunciarse sobre la propuesta de Acuerdo, su crédito no se considerará en el pasivo con derecho a voto correspondiente a su clase o categoría, y podrá cobrar su crédito respecto de los fiadores o codeudores, solidarios o subsidiarios, o avalistas en los términos originalmente pactados.

El fiador, codeudor, solidario o subsidiario, avalista, tercero poseedor de la finca hipotecada o propietario del bien prendado que hubiere pagado, de acuerdo a lo establecido en la letra b) del número 3) o en la letra b) del número 4) anteriores, podrá ejercer, según corresponda, su derecho de subrogación o reembolso, mediante un procedimiento incidental, ante el mismo tribunal que conoció y se pronunció sobre el Acuerdo, solicitando que éste se cumpla a su favor, mientras no se encuentren prescritas las acciones que de él resulten.

#### Párrafo 5. Del rechazo del Acuerdo de Reorganización Judicial {-}

##### Artículo 96.- Rechazo del Acuerdo. {-}

Si la propuesta de Acuerdo es rechazada por los acreedores por no haberse obtenido el quórum de aprobación necesario o porque el Deudor no otorga su consentimiento, el tribunal dictará la Resolución de Liquidación, de oficio y sin más trámite, en la misma Junta de Acreedores llamada a conocer y pronunciarse sobre el Acuerdo, salvo que la referida Junta disponga lo contrario por Quórum Especial.

En este caso, el Deudor deberá, a través del Veedor, publicar una nueva propuesta de Acuerdo en el Boletín Concursal y acompañarla al tribunal diez días antes de la Junta de Acreedores que tiene por objeto pronunciarse sobre ésta. El Deudor conservará la Protección Financiera Concursal hasta la celebración de dicha Junta, que deberá llevarse a cabo dentro de los veinte días siguientes a la que rechazó el Acuerdo.

Si el Deudor no presenta la nueva propuesta de Acuerdo dentro del plazo antes establecido, el tribunal dictará la Resolución de Liquidación, de oficio y sin más trámite.

La Junta de Acreedores que rechace la primera o segunda propuesta de Acuerdo, en su caso, deberá nominar a los Liquidadores titular y suplente, a los que el tribunal competente deberá designar con el carácter de definitivos.

#### Párrafo 6. De la nulidad y declaración de incumplimiento del Acuerdo de Reorganización Judicial {-}

##### Artículo 97.- Nulidad del Acuerdo. {-}

No se admitirán otras acciones en contra del Acuerdo que las fundadas en la ocultación o exageración del activo o del pasivo y de las que se hubiere tomado conocimiento después de haber vencido el plazo para impugnar el Acuerdo.

La declaración de nulidad del Acuerdo extingue de pleno derecho las cauciones que lo garantizan.

Las acciones de nulidad del Acuerdo podrán interponerse por cualquier interesado y prescribirán en el plazo de un año contado desde la fecha en que aquél comenzó a regir.

##### Artículo 98.- Acción de incumplimiento. {-}

El Acuerdo podrá declararse incumplido a solicitud de cualquiera de los acreedores a los que les afecte por inobservancia de sus estipulaciones.

Podrá también declararse incumplido si se hubiere agravado el mal estado de los negocios del Deudor de forma que haga temer un perjuicio para dichos acreedores.

Si la acción de incumplimiento se deduce sólo por la inobservancia de las estipulaciones de una de las clases o categorías del Acuerdo, el Deudor podrá enervar la acción cumpliendo dichas estipulaciones dentro del plazo de sesenta días contado desde la notificación de la acción. El Deudor podrá enervarla por una sola vez para cada categoría o clase del Acuerdo.

Las acciones de incumplimiento del Acuerdo prescribirán en el plazo de un año contado desde que se produce el incumplimiento.

La declaración de incumplimiento dejará sin efecto el Acuerdo, pero no extinguirá las cauciones que hubieren garantizado su ejecución total o parcial.

Las personas obligadas por las cauciones señaladas en el inciso anterior y los terceros poseedores de los bienes gravados con las mismas, según sea el caso, serán oídos en el juicio de declaración de incumplimiento y podrán impedir la continuación de éste enervando la acción mediante el cumplimiento del Acuerdo dentro de los tres días siguientes a la citación.

Las cantidades pagadas por el Deudor antes de la declaración de incumplimiento del Acuerdo y el producto obtenido durante el Procedimiento Concursal de Liquidación servirán de abono a la deuda en caso que la caución se extienda a toda la suma estipulada. Pero si comprende únicamente una parte de ella, sólo le servirá para imputarla a la parte que reste de la cuota no caucionada.

##### Artículo 99.- Procedimiento de declaración de nulidad e incumplimiento del Acuerdo. {-}

La nulidad o incumplimiento del Acuerdo se sujetarán al procedimiento del juicio sumario y será competente para conocer de estas acciones el tribunal ante el cual se tramitó el Acuerdo.

La resolución que acoja las acciones de nulidad o incumplimiento del Acuerdo será apelable en ambos efectos, pero el Deudor quedará de inmediato sujeto a la intervención de un Veedor que tendrá las facultades de interventor contenidas en los números 1), 7), 8) y 9) del artículo 25.

La declaración de nulidad o incumplimiento del Acuerdo no tendrá efecto retroactivo y no afectará la validez de los actos o contratos debidamente celebrados en el tiempo que media entre la resolución que aprueba el Acuerdo y la que declare la nulidad o el incumplimiento.

##### Artículo 100.- Inicio del Procedimiento Concursal de Liquidación. {-}

Una vez firme y ejecutoriada la resolución que declare la nulidad o el incumplimiento del Acuerdo, el mismo tribunal dictará la Resolución de Liquidación de la Empresa Deudora, de oficio y sin más trámite.

##### Artículo 101.- Designación del Liquidador. {-}

En la demanda de nulidad o de incumplimiento del Acuerdo, el demandante propondrá a un Liquidador titular y a uno suplente de la Nómina de Liquidadores vigente, debiendo el tribunal designarlos en la Resolución de Liquidación.

Si se interpusiere más de una demanda de nulidad o de incumplimiento del Acuerdo, el tribunal competente designará a los Liquidadores titular y suplente nominados en la primera demanda que se acoja.

### Título 3. Del Acuerdo de Reorganización Extrajudicial o Simplificado {-}

##### Artículo 102.- Legitimación. {-}

Toda Empresa Deudora podrá celebrar un Acuerdo de Reorganización Extrajudicial o Simplificado con sus acreedores y someterlo a aprobación judicial, conforme a lo establecido en el presente Título. Para los efectos de este Título se denominará indistintamente Empresa Deudora o Deudor.

##### Artículo 103.- Competencia. {-}

Será competente para aprobar el Acuerdo Simplificado el tribunal que hubiere sido competente para conocer de un Procedimiento Concursal de Reorganización del Deudor de acuerdo a esta ley.

##### Artículo 104.- Formalidades. {-}

El Acuerdo Simplificado deberá ser otorgado ante un ministro de fe o ante un ministro de fe de la Superintendencia, quien certificará, además, la personería de los representantes que concurran al otorgamiento de este instrumento, cuyas copias autorizadas deberán agregarse al Acuerdo respectivo.

##### Artículo 105.- Objeto. {-}

El Acuerdo Simplificado podrá versar sobre cualquier objeto tendiente a reestructurar los activos y pasivos del Deudor.

##### Artículo 106.- Normas aplicables. {-}

Serán aplicables al Acuerdo Simplificado, cuando corresponda y siempre que no contravengan lo dispuesto en el presente Párrafo, los Títulos 1 y 2 de este Capítulo, en lo relativo a los acuerdos por clases o categorías de acreedores, determinación del pasivo, propuestas alternativas, diferencias entre acreedores de igual clase o categoría, condonación o remisión de créditos, constitución de garantías, cláusulas de arbitraje, nombramiento del interventor y designación de la Comisión de Acreedores.

##### Artículo 107.- Requisitos. {-}

Para la aprobación judicial del Acuerdo Simplificado, éste deberá presentarse ante el tribunal competente junto con los antecedentes singularizados en el artículo 56, acompañado de un listado de todos los juicios y procesos administrativos seguidos contra el Deudor que tengan efectos patrimoniales, con indicación del tribunal, órgano de la Administración del Estado, rol o número de identificación y materias sobre las que tratan estos procesos.

Conjuntamente con la presentación del Acuerdo Simplificado, deberá presentarse un informe de un Veedor de la Nómina de Veedores, elegido por el Deudor y sus dos principales acreedores, que deberá contener la calificación fundada acerca de:

1. Si la propuesta es susceptible de ser cumplida, habida consideración de las condiciones del Deudor;

2. El monto probable de recuperación que le correspondería a cada acreedor en sus respectivas categorías, en caso de un Procedimiento Concursal de Liquidación, y

3. Si la determinación de los créditos y su preferencia, cuya propuesta acompañó el Deudor, se ajusta a esta ley.

##### Artículo 108.- Resolución de Reorganización Simplificada. {-}

Presentada la solicitud de aprobación judicial del Acuerdo Simplificado y hasta la aprobación judicial regulada en el artículo 112, el tribunal dispondrá:

a) La prohibición de solicitar la Liquidación Forzosa del Deudor y de iniciarse en su contra juicios ejecutivos, ejecuciones de cualquier clase o restitución en los juicios de arrendamiento. Lo anterior no se aplicará a los juicios laborales sobre obligaciones que gocen de preferencia de primera clase, suspendiéndose en ese caso sólo la ejecución y realización de bienes del Deudor, excepto los que el Deudor tuviere, en tal carácter, a favor de su cónyuge o de sus parientes o de los gerentes, administradores, apoderados con poder general de administración u otras personas que hayan tenido o tengan injerencia en la administración de sus negocios. Para estos efectos, se entenderá por parientes los ascendientes y descendientes y los colaterales por consanguinidad y afinidad hasta el cuarto grado, inclusive.

b) La suspensión de la tramitación de los procedimientos señalados en la letra a) precedente y la suspensión de los plazos de prescripción extintiva.

c) La prohibición al Deudor de gravar o enajenar sus bienes, salvo los que resulten estrictamente necesarios para la continuación de su giro.

##### Artículo 109.- Quórum. {-}

El Deudor deberá presentar el Acuerdo Simplificado suscrito por dos o más acreedores que representen al menos tres cuartas partes del total de su pasivo, correspondiente a su respectiva clase o categoría. Las Personas Relacionadas con el Deudor no podrán suscribir un Acuerdo Simplificado, ni sus créditos se considerarán en el monto del pasivo para los efectos de la determinación del quórum de aprobación del referido Acuerdo.

Los cesionarios de créditos adquiridos dentro de los treinta días anteriores a la fecha de la presentación a aprobación judicial del Acuerdo Simplificado tampoco se considerarán para el quórum señalado en el inciso anterior.

##### Artículo 110.- Publicidad. {-}

Junto con presentar al tribunal el Acuerdo Extrajudicial o Simplificado con los antecedentes señalados en el artículo 107, el Deudor deberá acompañar al Veedor copia de éstos para que los publique en el Boletín Concursal y los acompañe a los acreedores por medio de correos electrónicos, si lo tuvieren.

##### Artículo 111.- Impugnación. {-}

Podrán impugnar el Acuerdo Simplificado los acreedores disidentes y aquellos que demuestren haber sido omitidos de los antecedentes previstos en el artículo 107, siempre y cuando la impugnación se funde en alguna de las causales establecidas en el artículo 85 respecto de los Acuerdos de Reorganización Judicial, o bien en la existencia, los montos y las preferencias de sus créditos.

La impugnación deberá presentarse ante el tribunal competente dentro de los diez días siguientes a la publicación del Acuerdo Simplificado efectuada conforme al artículo anterior. Una copia de la impugnación señalada y de los antecedentes correspondientes deberán ser publicados en el Boletín Concursal por el Veedor.

Las impugnaciones al Acuerdo Simplificado se tramitarán como incidente y se fallarán conjuntamente en una audiencia única, que el tribunal citará para tal efecto y que se celebrará dentro de los diez días siguientes de vencido el plazo para impugnar. Esta audiencia será verbal y se llevará a cabo con los que asistan. La resolución que se pronuncie sobre las impugnaciones se publicará en el Boletín Concursal y será apelable en el solo efecto devolutivo.

##### Artículo 112.- Aprobación judicial. {-}

Dentro de los diez días siguientes a la publicación del Acuerdo Simplificado, el tribunal podrá citar a todos los acreedores a quienes les afecte el Acuerdo, para su aceptación ante el tribunal, la cual deberá contar con el quórum señalado en el artículo 109.

Una vez aceptado el Acuerdo Simplificado, o vencido el plazo señalado en el inciso anterior sin que el tribunal hubiere citado, y vencido el plazo para presentar impugnaciones sin que se hayan interpuesto o si, deducidas, se hubieren rechazado por resolución que se encuentre firme y ejecutoriada, el tribunal competente, previa verificación del cumplimiento de los requisitos legales, dictará la correspondiente resolución aprobando el Acuerdo Simplificado, debiendo el Veedor publicarla en el Boletín Concursal.

##### Artículo 113.- Efectos de la aprobación judicial. {-}

El Acuerdo Simplificado aprobado judicialmente de conformidad a las disposiciones anteriores producirá, cuando corresponda, los efectos previstos en el Párrafo 4 del Título 2 de este Capítulo, siempre que no contravenga lo dispuesto en el presente Párrafo.

##### Artículo 114.- Nulidad e Incumplimiento del Acuerdo Simplificado. {-}

Demandada la nulidad o el incumplimiento del Acuerdo Simplificado, se aplicará lo dispuesto en el Párrafo 6 del Título 2 de este Capítulo.



